//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFFM.Api.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RFFM.Api.Domain.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al enviar correo.
        /// </summary>
        public static string EmailPasswordErrorSending {
            get {
                return ResourceManager.GetString("EmailPasswordErrorSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haz clic en el siguiente enlace para continuar:.
        /// </summary>
        public static string ForgotPasswordActionInstructions {
            get {
                return ResourceManager.GetString("ForgotPasswordActionInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restablecer Contraseña.
        /// </summary>
        public static string ForgotPasswordActionText {
            get {
                return ResourceManager.GetString("ForgotPasswordActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El enlace expirará en 1 hora..
        /// </summary>
        public static string ForgotPasswordExpirationMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordExpirationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recibimos una solicitud para restablecer tu contraseña..
        /// </summary>
        public static string ForgotPasswordGreetingMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordGreetingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restablecer Contraseña.
        /// </summary>
        public static string ForgotPasswordIgnoreMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordIgnoreMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetea tu contraseña para Futbol Base.
        /// </summary>
        public static string ForgotPasswordResetSubject {
            get {
                return ResourceManager.GetString("ForgotPasswordResetSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se han proporcionado el usuario o la contraseña.
        /// </summary>
        public static string LoginEmptyUserOrPass {
            get {
                return ResourceManager.GetString("LoginEmptyUserOrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario o la password son erróneos.
        /// </summary>
        public static string LoginErrorUserOrPassword {
            get {
                return ResourceManager.GetString("LoginErrorUserOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todavía no te has registrado.
        /// </summary>
        public static string LoginUserNotRegistered {
            get {
                return ResourceManager.GetString("LoginUserNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ya existe.
        /// </summary>
        public static string RegisterEmailExistsAlready {
            get {
                return ResourceManager.GetString("RegisterEmailExistsAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al asignar el role del usuario.
        /// </summary>
        public static string RegisterFailedAssigningRole {
            get {
                return ResourceManager.GetString("RegisterFailedAssigningRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error inesperado durante el registro.
        /// </summary>
        public static string RegisterGeneralError {
            get {
                return ResourceManager.GetString("RegisterGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha proporcionado la contraseña.
        /// </summary>
        public static string RegisterPasswordNotClaim {
            get {
                return ResourceManager.GetString("RegisterPasswordNotClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña no cumple los requerimientos.
        /// </summary>
        public static string RegisterPassworNotMeetRequirements {
            get {
                return ResourceManager.GetString("RegisterPassworNotMeetRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña del token no ha sido encontrada.
        /// </summary>
        public static string RegisterSecretNotFound {
            get {
                return ResourceManager.GetString("RegisterSecretNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miembro del club.
        /// </summary>
        public static string RoleClubMember {
            get {
                return ResourceManager.GetString("RoleClubMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrenador.
        /// </summary>
        public static string RoleCoach {
            get {
                return ResourceManager.GetString("RoleCoach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directiva.
        /// </summary>
        public static string RoleDirective {
            get {
                return ResourceManager.GetString("RoleDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familiar del jugador.
        /// </summary>
        public static string RoleFamilyPlayer {
            get {
                return ResourceManager.GetString("RoleFamilyPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguidor.
        /// </summary>
        public static string RoleFollower {
            get {
                return ResourceManager.GetString("RoleFollower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugador.
        /// </summary>
        public static string RolePlayer {
            get {
                return ResourceManager.GetString("RolePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede crear un club si el role del usuario no es Directivo o Entrenador.
        /// </summary>
        public static string UserClubNotRolePermissive {
            get {
                return ResourceManager.GetString("UserClubNotRolePermissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El identificador del club no puede ser nulo.
        /// </summary>
        public static string UserClubNotValidClubId {
            get {
                return ResourceManager.GetString("UserClubNotValidClubId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El identificador del usario es nulo.
        /// </summary>
        public static string UserClubNotValidUserId {
            get {
                return ResourceManager.GetString("UserClubNotValidUserId", resourceCulture);
            }
        }
    }
}
