CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'app') THEN
            CREATE SCHEMA app;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."AssistanceTypes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(256) NOT NULL,
        "Points" integer NOT NULL,
        CONSTRAINT "PK_AssistanceTypes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."Categories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(500) NOT NULL,
        CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."ConfigurationCoach" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CoachId" text NOT NULL,
        "PreferredClubId" character varying(50),
        "PreferredTeamId" character varying(50),
        CONSTRAINT "PK_ConfigurationCoach" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."ConvocationStatuses" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(256) NOT NULL,
        CONSTRAINT "PK_ConvocationStatuses" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."Countries" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(200) NOT NULL,
        "Code" text NOT NULL,
        CONSTRAINT "PK_Countries" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."DemarcationMaster" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(50) NOT NULL,
        CONSTRAINT "PK_DemarcationMaster" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."ExcuseTypes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Justified" boolean NOT NULL,
        CONSTRAINT "PK_ExcuseTypes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."Memberships" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Key" character varying(100) NOT NULL,
        CONSTRAINT "PK_Memberships" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."PaymentPlans" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(200) NOT NULL,
        "Description" character varying(1000),
        "PriceCents" integer NOT NULL,
        "BillingPeriod" integer NOT NULL,
        "AllowedClubs" integer NOT NULL,
        "AllowedTeams" integer NOT NULL,
        "AllowedUsers" integer NOT NULL,
        CONSTRAINT "PK_PaymentPlans" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."PlayTypes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(250) NOT NULL,
        CONSTRAINT "PK_PlayTypes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."PointsTypes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        CONSTRAINT "PK_PointsTypes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."Rivals" (
        "Id" text NOT NULL,
        "Name" character varying(100) NOT NULL,
        "UrlPhoto" character varying(256),
        CONSTRAINT "PK_Rivals" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."Seasons" (
        "Id" text NOT NULL,
        "Name" character varying(200) NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Seasons" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."SportEventTypes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(256) NOT NULL,
        CONSTRAINT "PK_SportEventTypes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."TacticalGoals" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        CONSTRAINT "PK_TacticalGoals" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."TaskTrainingBases" (
        "Id" text NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Description" character varying(2000) NOT NULL,
        "PlayersNumber" integer NOT NULL,
        "GoalPeekersNumber" integer NOT NULL,
        "DurationTotal" integer NOT NULL,
        "FieldSpace" character varying(100) NOT NULL,
        "Points" integer NOT NULL,
        "UrlImage" character varying(500),
        "Discriminator" character varying(13) NOT NULL,
        "Series" integer,
        "DurationSeries" integer,
        "RestSeries" integer,
        "Time" interval,
        "TouchesNumber" integer,
        "WildCards" integer,
        "TechnicalTaskTraining_TouchesNumber" integer,
        "TechnicalTaskTraining_WildCards" integer,
        CONSTRAINT "PK_TaskTrainingBases" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."TechnicalGoals" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        CONSTRAINT "PK_TechnicalGoals" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."TechnicalTypes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        CONSTRAINT "PK_TechnicalTypes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."Leagues" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(500) NOT NULL,
        "CategoryId" integer NOT NULL,
        CONSTRAINT "PK_Leagues" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Leagues_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES app."Categories" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."Clubs" (
        "Id" text NOT NULL,
        "Name" character varying(200) NOT NULL,
        "CountryId" integer NOT NULL,
        "ShieldUrl" character varying(500),
        "InvitationCode" character varying(8),
        CONSTRAINT "PK_Clubs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Clubs_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES app."Countries" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."Subscriptions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" character varying(450) NOT NULL,
        "PaymentPlanId" integer NOT NULL,
        "StartDate" timestamp with time zone NOT NULL,
        "EndDate" timestamp with time zone NOT NULL,
        "Status" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Subscriptions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Subscriptions_PaymentPlans_PaymentPlanId" FOREIGN KEY ("PaymentPlanId") REFERENCES app."PaymentPlans" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."Materials" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "TaskTrainingBaseId" text,
        CONSTRAINT "PK_Materials" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Materials_TaskTrainingBases_TaskTrainingBaseId" FOREIGN KEY ("TaskTrainingBaseId") REFERENCES app."TaskTrainingBases" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."Technicals" (
        "Id" text NOT NULL,
        "Name" character varying(500) NOT NULL,
        "TechnicalTypeId" integer NOT NULL,
        CONSTRAINT "PK_Technicals" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Technicals_TechnicalTypes_TechnicalTypeId" FOREIGN KEY ("TechnicalTypeId") REFERENCES app."TechnicalTypes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."Players" (
        "Id" text NOT NULL,
        "Name" character varying(500) NOT NULL,
        "LastName" character varying(2000),
        "UrlPhoto" character varying(500),
        "Alias" character varying(100) NOT NULL,
        "BirthDate" timestamp with time zone,
        "Dni" character varying(20),
        "ClubId" text NOT NULL,
        CONSTRAINT "PK_Players" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Players_Clubs_ClubId" FOREIGN KEY ("ClubId") REFERENCES app."Clubs" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."Teams" (
        "Id" text NOT NULL,
        "Name" character varying(500) NOT NULL,
        "CategoryId" integer NOT NULL,
        "LeagueId" integer,
        "LeagueGroup" integer,
        "UrlPhoto" character varying(500),
        "ClubId" text NOT NULL,
        "SeasonId" text NOT NULL,
        CONSTRAINT "PK_Teams" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Teams_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES app."Categories" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Teams_Clubs_ClubId" FOREIGN KEY ("ClubId") REFERENCES app."Clubs" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Teams_Leagues_LeagueId" FOREIGN KEY ("LeagueId") REFERENCES app."Leagues" ("Id"),
        CONSTRAINT "FK_Teams_Seasons_SeasonId" FOREIGN KEY ("SeasonId") REFERENCES app."Seasons" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."UserClubs" (
        "Id" text NOT NULL,
        "ApplicationUserId" character varying(450) NOT NULL,
        "ClubId" text NOT NULL,
        "RoleId" integer NOT NULL,
        "IsCreator" boolean NOT NULL,
        CONSTRAINT "PK_UserClubs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UserClubs_Clubs_ClubId" FOREIGN KEY ("ClubId") REFERENCES app."Clubs" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserClubs_Memberships_RoleId" FOREIGN KEY ("RoleId") REFERENCES app."Memberships" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."TrainingPointsReports" (
        "Id" text NOT NULL,
        "TotalPoints" integer NOT NULL,
        "TrainingNumber" integer NOT NULL,
        "AssistancePoint" integer NOT NULL,
        "TecnicalPoints" integer NOT NULL,
        "AttitudePoints" integer NOT NULL,
        "TacticalPoints" integer NOT NULL,
        "PhysicalPoints" integer NOT NULL,
        "PlayerId" text NOT NULL,
        "SeasonId" text NOT NULL,
        CONSTRAINT "PK_TrainingPointsReports" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TrainingPointsReports_Players_PlayerId" FOREIGN KEY ("PlayerId") REFERENCES app."Players" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_TrainingPointsReports_Seasons_SeasonId" FOREIGN KEY ("SeasonId") REFERENCES app."Seasons" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."SportEvents" (
        "Id" text NOT NULL,
        "Name" character varying(256) NOT NULL,
        "EveDateTime" timestamp with time zone NOT NULL,
        "StartTime" timestamp with time zone NOT NULL,
        "EndTime" timestamp with time zone,
        "ArrivalDate" timestamp with time zone,
        "Location" character varying(512),
        "Description" character varying(2048),
        "EventTypeId" integer NOT NULL,
        "TeamId" text NOT NULL,
        "RivalId" text,
        "TeamId1" text,
        "IsHomeMatch" boolean NOT NULL DEFAULT TRUE,
        "CodActa" character varying(100),
        "LocalGoals" text,
        "VisitorGoals" text,
        CONSTRAINT "PK_SportEvents" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SportEvents_Rivals_RivalId" FOREIGN KEY ("RivalId") REFERENCES app."Rivals" ("Id"),
        CONSTRAINT "FK_SportEvents_SportEventTypes_EventTypeId" FOREIGN KEY ("EventTypeId") REFERENCES app."SportEventTypes" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_SportEvents_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES app."Teams" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_SportEvents_Teams_TeamId1" FOREIGN KEY ("TeamId1") REFERENCES app."Teams" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."TeamPlayers" (
        "Id" text NOT NULL,
        "TeamId" text NOT NULL,
        "PlayerId" text NOT NULL,
        "JoinedDate" timestamp with time zone NOT NULL,
        "LeftDate" timestamp with time zone,
        CONSTRAINT "PK_TeamPlayers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TeamPlayers_Players_PlayerId" FOREIGN KEY ("PlayerId") REFERENCES app."Players" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_TeamPlayers_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES app."Teams" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."SessionTrainings" (
        "Id" text NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Description" character varying(2000) NOT NULL,
        "Date" timestamp with time zone NOT NULL,
        "StartTime" interval NOT NULL,
        "EndTime" interval,
        "Location" character varying(500),
        "SportEventId" text NOT NULL,
        "TeamId" text NOT NULL,
        "UrlImage" character varying(500),
        CONSTRAINT "PK_SessionTrainings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SessionTrainings_SportEvents_SportEventId" FOREIGN KEY ("SportEventId") REFERENCES app."SportEvents" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_SessionTrainings_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES app."Teams" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."Convocations" (
        "Id" text NOT NULL,
        "SportEventId" text NOT NULL,
        "TeamPlayerId" text NOT NULL,
        "AssistanceTypeId" integer NOT NULL,
        "ResponseDateTime" timestamp with time zone,
        "ConvocationStatusId" integer,
        "ExcuseTypeId" integer,
        CONSTRAINT "PK_Convocations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Convocations_AssistanceTypes_AssistanceTypeId" FOREIGN KEY ("AssistanceTypeId") REFERENCES app."AssistanceTypes" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Convocations_ConvocationStatuses_ConvocationStatusId" FOREIGN KEY ("ConvocationStatusId") REFERENCES app."ConvocationStatuses" ("Id"),
        CONSTRAINT "FK_Convocations_ExcuseTypes_ExcuseTypeId" FOREIGN KEY ("ExcuseTypeId") REFERENCES app."ExcuseTypes" ("Id"),
        CONSTRAINT "FK_Convocations_SportEvents_SportEventId" FOREIGN KEY ("SportEventId") REFERENCES app."SportEvents" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Convocations_TeamPlayers_TeamPlayerId" FOREIGN KEY ("TeamPlayerId") REFERENCES app."TeamPlayers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."TeamPlayerContactInfos" (
        "TeamPlayerId" text NOT NULL,
        "Address_Street" character varying(200),
        "Address_City" character varying(100),
        "Address_Province" character varying(100),
        "Address_PostalCode" character varying(20),
        "Address_Country" character varying(100),
        "Phone" character varying(15),
        "Email" character varying(255),
        CONSTRAINT "PK_TeamPlayerContactInfos" PRIMARY KEY ("TeamPlayerId"),
        CONSTRAINT "FK_TeamPlayerContactInfos_TeamPlayers_TeamPlayerId" FOREIGN KEY ("TeamPlayerId") REFERENCES app."TeamPlayers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."TeamPlayerDemarcations" (
        "TeamPlayerId" text NOT NULL,
        "PossibleDemarcationIds" text,
        "ActivePositionId" integer NOT NULL,
        CONSTRAINT "PK_TeamPlayerDemarcations" PRIMARY KEY ("TeamPlayerId"),
        CONSTRAINT "FK_TeamPlayerDemarcations_TeamPlayers_TeamPlayerId" FOREIGN KEY ("TeamPlayerId") REFERENCES app."TeamPlayers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."TeamPlayerDorsals" (
        "TeamPlayerId" text NOT NULL,
        "Number" integer NOT NULL,
        CONSTRAINT "PK_TeamPlayerDorsals" PRIMARY KEY ("TeamPlayerId"),
        CONSTRAINT "FK_TeamPlayerDorsals_TeamPlayers_TeamPlayerId" FOREIGN KEY ("TeamPlayerId") REFERENCES app."TeamPlayers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."TeamPlayerFamilies" (
        "Id" text NOT NULL,
        "Address_Street" character varying(200),
        "Address_City" character varying(100),
        "Address_Province" character varying(100),
        "Address_PostalCode" character varying(20),
        "Address_Country" character varying(100),
        "Address_Id" text,
        "Phone" character varying(15),
        "Email" character varying(255),
        "Name" character varying(100),
        "FamilyMember" character varying(50),
        "TeamPlayerId" text NOT NULL,
        CONSTRAINT "PK_TeamPlayerFamilies" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TeamPlayerFamilies_TeamPlayers_TeamPlayerId" FOREIGN KEY ("TeamPlayerId") REFERENCES app."TeamPlayers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."TeamPlayerPhysicalAttributes" (
        "TeamPlayerId" text NOT NULL,
        "Height" numeric(5,2),
        "Weight" numeric(5,2),
        "DominantFoot" integer,
        CONSTRAINT "PK_TeamPlayerPhysicalAttributes" PRIMARY KEY ("TeamPlayerId"),
        CONSTRAINT "FK_TeamPlayerPhysicalAttributes_TeamPlayers_TeamPlayerId" FOREIGN KEY ("TeamPlayerId") REFERENCES app."TeamPlayers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."TaskTrainings" (
        "Id" text NOT NULL,
        "Order" integer NOT NULL,
        "SessionTrainingId" text NOT NULL,
        CONSTRAINT "PK_TaskTrainings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TaskTrainings_SessionTrainings_SessionTrainingId" FOREIGN KEY ("SessionTrainingId") REFERENCES app."SessionTrainings" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_TaskTrainings_TaskTrainingBases_Id" FOREIGN KEY ("Id") REFERENCES app."TaskTrainingBases" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE TABLE app."ConvocationHistories" (
        "Id" text NOT NULL,
        "ConvocationId" text NOT NULL,
        "UserId" text NOT NULL,
        "ChangeDateTime" timestamp with time zone NOT NULL,
        "OldStatusId" integer,
        "NewStatusId" integer NOT NULL,
        CONSTRAINT "PK_ConvocationHistories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ConvocationHistories_Convocations_ConvocationId" FOREIGN KEY ("ConvocationId") REFERENCES app."Convocations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    INSERT INTO app."AssistanceTypes" ("Id", "Name", "Points")
    VALUES (1, 'Asiste', 5);
    INSERT INTO app."AssistanceTypes" ("Id", "Name", "Points")
    VALUES (2, 'No asiste con excusa', 0);
    INSERT INTO app."AssistanceTypes" ("Id", "Name", "Points")
    VALUES (3, 'No asiste sin excusa', 0);
    INSERT INTO app."AssistanceTypes" ("Id", "Name", "Points")
    VALUES (4, 'Llega tarde', 2);
    INSERT INTO app."AssistanceTypes" ("Id", "Name", "Points")
    VALUES (5, 'Disponible', 0);
    INSERT INTO app."AssistanceTypes" ("Id", "Name", "Points")
    VALUES (6, 'No disponible', 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    INSERT INTO app."Categories" ("Id", "Name")
    VALUES (1, 'Categoría Nacional');
    INSERT INTO app."Categories" ("Id", "Name")
    VALUES (2, 'Aficionados');
    INSERT INTO app."Categories" ("Id", "Name")
    VALUES (3, 'Juveniles');
    INSERT INTO app."Categories" ("Id", "Name")
    VALUES (4, 'Cadetes');
    INSERT INTO app."Categories" ("Id", "Name")
    VALUES (5, 'Infantiles');
    INSERT INTO app."Categories" ("Id", "Name")
    VALUES (6, 'Alevines');
    INSERT INTO app."Categories" ("Id", "Name")
    VALUES (7, 'Benjamines');
    INSERT INTO app."Categories" ("Id", "Name")
    VALUES (8, 'Prebenjamines');
    INSERT INTO app."Categories" ("Id", "Name")
    VALUES (9, 'Debutantes');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    INSERT INTO app."ConvocationStatuses" ("Id", "Name")
    VALUES (1, 'Pending');
    INSERT INTO app."ConvocationStatuses" ("Id", "Name")
    VALUES (2, 'Accepted');
    INSERT INTO app."ConvocationStatuses" ("Id", "Name")
    VALUES (3, 'Declined');
    INSERT INTO app."ConvocationStatuses" ("Id", "Name")
    VALUES (4, 'Justified');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (1, 'AF', 'Afganistán');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (2, 'AL', 'Albania');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (3, 'DE', 'Alemania');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (4, 'AD', 'Andorra');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (5, 'AO', 'Angola');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (6, 'AG', 'Antigua y Barbuda');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (7, 'SA', 'Arabia Saudita');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (8, 'DZ', 'Argelia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (9, 'AR', 'Argentina');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (10, 'AM', 'Armenia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (11, 'AU', 'Australia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (12, 'AT', 'Austria');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (13, 'AZ', 'Azerbaiyán');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (14, 'BS', 'Bahamas');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (15, 'BD', 'Bangladés');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (16, 'BB', 'Barbados');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (17, 'BH', 'Baréin');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (18, 'BE', 'Bélgica');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (19, 'BZ', 'Belice');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (20, 'BJ', 'Benín');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (21, 'BY', 'Bielorrusia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (22, 'MM', 'Birmania (Myanmar)');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (23, 'BO', 'Bolivia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (24, 'BA', 'Bosnia y Herzegovina');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (25, 'BW', 'Botsuana');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (26, 'BR', 'Brasil');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (27, 'BN', 'Brunéi');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (28, 'BG', 'Bulgaria');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (29, 'BF', 'Burkina Faso');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (30, 'BI', 'Burundi');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (31, 'BT', 'Bután');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (32, 'CV', 'Cabo Verde');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (33, 'KH', 'Camboya');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (34, 'CM', 'Camerún');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (35, 'CA', 'Canadá');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (36, 'QA', 'Catar');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (37, 'TD', 'Chad');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (38, 'CL', 'Chile');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (39, 'CN', 'China');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (40, 'CY', 'Chipre');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (41, 'CO', 'Colombia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (42, 'KM', 'Comoras');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (43, 'KP', 'Corea del Norte');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (44, 'KR', 'Corea del Sur');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (45, 'CI', 'Costa de Marfil');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (46, 'CR', 'Costa Rica');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (47, 'HR', 'Croacia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (48, 'CU', 'Cuba');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (49, 'DK', 'Dinamarca');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (50, 'DM', 'Dominica');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (51, 'EC', 'Ecuador');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (52, 'EG', 'Egipto');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (53, 'SV', 'El Salvador');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (54, 'AE', 'Emiratos Árabes Unidos');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (55, 'ER', 'Eritrea');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (56, 'SK', 'Eslovaquia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (57, 'SI', 'Eslovenia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (58, 'ES', 'España');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (59, 'US', 'Estados Unidos');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (60, 'EE', 'Estonia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (61, 'SZ', 'Esuatini');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (62, 'ET', 'Etiopía');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (63, 'PH', 'Filipinas');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (64, 'FI', 'Finlandia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (65, 'FJ', 'Fiyi');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (66, 'FR', 'Francia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (67, 'GA', 'Gabón');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (68, 'GM', 'Gambia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (69, 'GE', 'Georgia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (70, 'GH', 'Ghana');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (71, 'GD', 'Granada');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (72, 'GR', 'Grecia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (73, 'GT', 'Guatemala');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (74, 'GN', 'Guinea');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (75, 'GW', 'Guinea-Bisáu');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (76, 'GY', 'Guyana');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (77, 'HT', 'Haití');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (78, 'HN', 'Honduras');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (79, 'HU', 'Hungría');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (80, 'IN', 'India');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (81, 'ID', 'Indonesia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (82, 'IQ', 'Irak');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (83, 'IR', 'Irán');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (84, 'IE', 'Irlanda');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (85, 'IS', 'Islandia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (86, 'IL', 'Israel');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (87, 'IT', 'Italia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (88, 'JM', 'Jamaica');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (89, 'JP', 'Japón');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (90, 'JO', 'Jordania');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (91, 'KZ', 'Kazajistán');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (92, 'KE', 'Kenia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (93, 'KG', 'Kirguistán');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (94, 'KI', 'Kiribati');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (95, 'XK', 'Kosovo');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (96, 'KW', 'Kuwait');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (97, 'LA', 'Laos');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (98, 'LV', 'Letonia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (99, 'LB', 'Líbano');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (100, 'LR', 'Liberia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (101, 'LY', 'Libia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (102, 'LI', 'Liechtenstein');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (103, 'LT', 'Lituania');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (104, 'LU', 'Luxemburgo');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (105, 'MG', 'Madagascar');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (106, 'MY', 'Malasia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (107, 'MW', 'Malaui');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (108, 'MV', 'Maldivas');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (109, 'ML', 'Malí');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (110, 'MT', 'Malta');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (111, 'MA', 'Marruecos');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (112, 'MU', 'Mauricio');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (113, 'MR', 'Mauritania');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (114, 'MX', 'México');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (115, 'FM', 'Micronesia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (116, 'MD', 'Moldavia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (117, 'MC', 'Mónaco');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (118, 'MN', 'Mongolia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (119, 'ME', 'Montenegro');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (120, 'MZ', 'Mozambique');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (121, 'NA', 'Namibia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (122, 'NR', 'Nauru');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (123, 'NP', 'Nepal');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (124, 'NI', 'Nicaragua');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (125, 'NE', 'Níger');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (126, 'NG', 'Nigeria');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (127, 'NO', 'Noruega');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (128, 'NZ', 'Nueva Zelanda');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (129, 'OM', 'Omán');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (130, 'NL', 'Países Bajos');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (131, 'PK', 'Pakistán');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (132, 'PW', 'Palaos');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (133, 'PA', 'Panamá');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (134, 'PG', 'Papúa Nueva Guinea');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (135, 'PY', 'Paraguay');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (136, 'PE', 'Perú');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (137, 'PL', 'Polonia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (138, 'PT', 'Portugal');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (139, 'GB', 'Reino Unido');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (140, 'CF', 'República Centroafricana');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (141, 'CZ', 'República Checa');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (142, 'DO', 'República Dominicana');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (143, 'RW', 'Ruanda');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (144, 'RO', 'Rumanía');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (145, 'RU', 'Rusia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (146, 'WS', 'Samoa');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (147, 'KN', 'San Cristóbal y Nieves');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (148, 'SM', 'San Marino');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (149, 'VC', 'San Vicente y las Granadinas');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (150, 'LC', 'Santa Lucía');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (151, 'ST', 'Santo Tomé y Príncipe');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (152, 'SN', 'Senegal');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (153, 'RS', 'Serbia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (154, 'SC', 'Seychelles');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (155, 'SL', 'Sierra Leona');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (156, 'SG', 'Singapur');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (157, 'SY', 'Siria');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (158, 'SO', 'Somalia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (159, 'LK', 'Sri Lanka');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (160, 'ZA', 'Sudáfrica');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (161, 'SD', 'Sudán');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (162, 'SS', 'Sudán del Sur');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (163, 'SE', 'Suecia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (164, 'CH', 'Suiza');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (165, 'SR', 'Surinam');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (166, 'TH', 'Tailandia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (167, 'TZ', 'Tanzania');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (168, 'TJ', 'Tayikistán');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (169, 'TL', 'Timor Oriental');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (170, 'TG', 'Togo');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (171, 'TO', 'Tonga');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (172, 'TT', 'Trinidad y Tobago');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (173, 'TN', 'Túnez');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (174, 'TM', 'Turkmenistán');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (175, 'TR', 'Turquía');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (176, 'TV', 'Tuvalu');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (177, 'UA', 'Ucrania');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (178, 'UG', 'Uganda');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (179, 'UY', 'Uruguay');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (180, 'UZ', 'Uzbekistán');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (181, 'VU', 'Vanuatu');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (182, 'VA', 'Vaticano');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (183, 'VE', 'Venezuela');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (184, 'VN', 'Vietnam');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (185, 'YE', 'Yemen');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (186, 'DJ', 'Yibuti');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (187, 'ZM', 'Zambia');
    INSERT INTO app."Countries" ("Id", "Code", "Name")
    VALUES (188, 'ZW', 'Zimbabue');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    INSERT INTO app."DemarcationMaster" ("Id", "Name")
    VALUES (1, 'Portero');
    INSERT INTO app."DemarcationMaster" ("Id", "Name")
    VALUES (2, 'Lateral Izquierdo');
    INSERT INTO app."DemarcationMaster" ("Id", "Name")
    VALUES (3, 'Lateral Derecho');
    INSERT INTO app."DemarcationMaster" ("Id", "Name")
    VALUES (4, 'Defensa Central');
    INSERT INTO app."DemarcationMaster" ("Id", "Name")
    VALUES (5, 'Líbero');
    INSERT INTO app."DemarcationMaster" ("Id", "Name")
    VALUES (6, 'Medio Centro');
    INSERT INTO app."DemarcationMaster" ("Id", "Name")
    VALUES (7, 'Medio Centro Defensivo');
    INSERT INTO app."DemarcationMaster" ("Id", "Name")
    VALUES (8, 'Mediocampista ofensivo');
    INSERT INTO app."DemarcationMaster" ("Id", "Name")
    VALUES (9, 'Mediocampista Izquierdo');
    INSERT INTO app."DemarcationMaster" ("Id", "Name")
    VALUES (10, 'Mediocampista Derecho');
    INSERT INTO app."DemarcationMaster" ("Id", "Name")
    VALUES (11, 'Delantero Centro');
    INSERT INTO app."DemarcationMaster" ("Id", "Name")
    VALUES (12, 'Segundo Delantero');
    INSERT INTO app."DemarcationMaster" ("Id", "Name")
    VALUES (13, 'Extremo Izquierdo');
    INSERT INTO app."DemarcationMaster" ("Id", "Name")
    VALUES (14, 'Extremo Derecho');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    INSERT INTO app."ExcuseTypes" ("Id", "Justified", "Name")
    VALUES (1, TRUE, 'Injury');
    INSERT INTO app."ExcuseTypes" ("Id", "Justified", "Name")
    VALUES (2, TRUE, 'Study');
    INSERT INTO app."ExcuseTypes" ("Id", "Justified", "Name")
    VALUES (3, TRUE, 'Ill');
    INSERT INTO app."ExcuseTypes" ("Id", "Justified", "Name")
    VALUES (4, TRUE, 'Family Problem');
    INSERT INTO app."ExcuseTypes" ("Id", "Justified", "Name")
    VALUES (5, FALSE, 'Family Event');
    INSERT INTO app."ExcuseTypes" ("Id", "Justified", "Name")
    VALUES (6, FALSE, 'Birthday Event');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    INSERT INTO app."Materials" ("Id", "Name", "TaskTrainingBaseId")
    VALUES (1, 'Conos', NULL);
    INSERT INTO app."Materials" ("Id", "Name", "TaskTrainingBaseId")
    VALUES (2, 'Balones', NULL);
    INSERT INTO app."Materials" ("Id", "Name", "TaskTrainingBaseId")
    VALUES (3, 'Chalecos', NULL);
    INSERT INTO app."Materials" ("Id", "Name", "TaskTrainingBaseId")
    VALUES (4, 'Picas', NULL);
    INSERT INTO app."Materials" ("Id", "Name", "TaskTrainingBaseId")
    VALUES (5, 'Escaleras de agilidad', NULL);
    INSERT INTO app."Materials" ("Id", "Name", "TaskTrainingBaseId")
    VALUES (6, 'Vallas', NULL);
    INSERT INTO app."Materials" ("Id", "Name", "TaskTrainingBaseId")
    VALUES (7, 'Setas', NULL);
    INSERT INTO app."Materials" ("Id", "Name", "TaskTrainingBaseId")
    VALUES (8, 'Ninguno', NULL);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    INSERT INTO app."Memberships" ("Id", "Key", "Name")
    VALUES (1, 'Directive', 'Directive');
    INSERT INTO app."Memberships" ("Id", "Key", "Name")
    VALUES (2, 'Coach', 'Coach');
    INSERT INTO app."Memberships" ("Id", "Key", "Name")
    VALUES (3, 'ClubMember', 'Club member');
    INSERT INTO app."Memberships" ("Id", "Key", "Name")
    VALUES (4, 'Player', 'Player');
    INSERT INTO app."Memberships" ("Id", "Key", "Name")
    VALUES (5, 'FamilyPlayer', 'FamilyMembers player');
    INSERT INTO app."Memberships" ("Id", "Key", "Name")
    VALUES (6, 'Follower', 'Follower');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    INSERT INTO app."PlayTypes" ("Id", "Name")
    VALUES (1, 'Fútbol 11');
    INSERT INTO app."PlayTypes" ("Id", "Name")
    VALUES (2, 'Fútbol 7');
    INSERT INTO app."PlayTypes" ("Id", "Name")
    VALUES (3, 'Fútbol Sala');
    INSERT INTO app."PlayTypes" ("Id", "Name")
    VALUES (4, 'Fútbol-5');
    INSERT INTO app."PlayTypes" ("Id", "Name")
    VALUES (5, 'Fútbol-Playa');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    INSERT INTO app."PointsTypes" ("Id", "Name")
    VALUES (1, 'Físico');
    INSERT INTO app."PointsTypes" ("Id", "Name")
    VALUES (2, 'Técnico');
    INSERT INTO app."PointsTypes" ("Id", "Name")
    VALUES (3, 'Táctico');
    INSERT INTO app."PointsTypes" ("Id", "Name")
    VALUES (4, 'Psicológico');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    INSERT INTO app."SportEventTypes" ("Id", "Name")
    VALUES (1, 'Partido');
    INSERT INTO app."SportEventTypes" ("Id", "Name")
    VALUES (2, 'Entrenamiento');
    INSERT INTO app."SportEventTypes" ("Id", "Name")
    VALUES (3, 'Reunión');
    INSERT INTO app."SportEventTypes" ("Id", "Name")
    VALUES (4, 'Amistoso');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    INSERT INTO app."TacticalGoals" ("Id", "Name")
    VALUES (1, 'Marcaje');
    INSERT INTO app."TacticalGoals" ("Id", "Name")
    VALUES (2, 'Repliegue');
    INSERT INTO app."TacticalGoals" ("Id", "Name")
    VALUES (3, 'Cobertura');
    INSERT INTO app."TacticalGoals" ("Id", "Name")
    VALUES (4, 'Permuta');
    INSERT INTO app."TacticalGoals" ("Id", "Name")
    VALUES (5, 'Vigilancia defensiva');
    INSERT INTO app."TacticalGoals" ("Id", "Name")
    VALUES (6, 'Temporizaciones');
    INSERT INTO app."TacticalGoals" ("Id", "Name")
    VALUES (7, 'Entrada');
    INSERT INTO app."TacticalGoals" ("Id", "Name")
    VALUES (8, 'Carga');
    INSERT INTO app."TacticalGoals" ("Id", "Name")
    VALUES (9, 'Anticipación');
    INSERT INTO app."TacticalGoals" ("Id", "Name")
    VALUES (10, 'Intercepción');
    INSERT INTO app."TacticalGoals" ("Id", "Name")
    VALUES (11, 'Pressing');
    INSERT INTO app."TacticalGoals" ("Id", "Name")
    VALUES (12, 'Pressing tras pérdida');
    INSERT INTO app."TacticalGoals" ("Id", "Name")
    VALUES (13, 'Desmarques');
    INSERT INTO app."TacticalGoals" ("Id", "Name")
    VALUES (14, 'Apoyos');
    INSERT INTO app."TacticalGoals" ("Id", "Name")
    VALUES (15, 'Ataque');
    INSERT INTO app."TacticalGoals" ("Id", "Name")
    VALUES (16, 'Contraataque');
    INSERT INTO app."TacticalGoals" ("Id", "Name")
    VALUES (17, 'Ritmo de juego');
    INSERT INTO app."TacticalGoals" ("Id", "Name")
    VALUES (18, 'Cambios de ritmo');
    INSERT INTO app."TacticalGoals" ("Id", "Name")
    VALUES (19, 'Conservación de balón');
    INSERT INTO app."TacticalGoals" ("Id", "Name")
    VALUES (20, 'Cambios de orientación');
    INSERT INTO app."TacticalGoals" ("Id", "Name")
    VALUES (21, 'Progresión');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    INSERT INTO app."TechnicalGoals" ("Id", "Name")
    VALUES (1, 'Control');
    INSERT INTO app."TechnicalGoals" ("Id", "Name")
    VALUES (2, 'Pase');
    INSERT INTO app."TechnicalGoals" ("Id", "Name")
    VALUES (3, 'Regate');
    INSERT INTO app."TechnicalGoals" ("Id", "Name")
    VALUES (4, 'Tiro');
    INSERT INTO app."TechnicalGoals" ("Id", "Name")
    VALUES (5, 'Cabeza');
    INSERT INTO app."TechnicalGoals" ("Id", "Name")
    VALUES (6, 'Robo');
    INSERT INTO app."TechnicalGoals" ("Id", "Name")
    VALUES (7, 'Conducción');
    INSERT INTO app."TechnicalGoals" ("Id", "Name")
    VALUES (8, 'Entrada');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    INSERT INTO app."TechnicalTypes" ("Id", "Name")
    VALUES (1, 'Delegado');
    INSERT INTO app."TechnicalTypes" ("Id", "Name")
    VALUES (2, 'Delegado de campo');
    INSERT INTO app."TechnicalTypes" ("Id", "Name")
    VALUES (3, 'Auxiliar');
    INSERT INTO app."TechnicalTypes" ("Id", "Name")
    VALUES (4, 'Entrenador');
    INSERT INTO app."TechnicalTypes" ("Id", "Name")
    VALUES (5, 'Segundo Entrenador');
    INSERT INTO app."TechnicalTypes" ("Id", "Name")
    VALUES (6, 'Entrenador de porteros');
    INSERT INTO app."TechnicalTypes" ("Id", "Name")
    VALUES (7, 'Preparador físico');
    INSERT INTO app."TechnicalTypes" ("Id", "Name")
    VALUES (8, 'Médico');
    INSERT INTO app."TechnicalTypes" ("Id", "Name")
    VALUES (9, 'Psicólogo');
    INSERT INTO app."TechnicalTypes" ("Id", "Name")
    VALUES (10, 'Analista táctico');
    INSERT INTO app."TechnicalTypes" ("Id", "Name")
    VALUES (11, 'Nutricionista');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (1, 1, 'COPA RFEF FASE AUTONÓMICA');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (2, 1, 'FINAL COPA RFEF FASE AUTONÓMICA');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (3, 1, 'PLAY OFF TERCERA FEDERACION');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (4, 1, 'TERCERA FEDERACION RFEF');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (5, 2, 'COPA RFFM PRIMERA DIVISION AUTONOMICA AFICIONADOS');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (6, 2, 'FASE FINAL COPA DE AFICIONADOS RFFM TEMP 2024/25');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (7, 2, 'FINAL COPA PRIMERA DIVISION AUTONOMICA AFICIONADO RFFM');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (8, 2, 'PRIMERA DIVISION AUTONOMICA AFICIONADO');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (9, 2, 'PREFERENTE AFICIONADO');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (10, 2, 'PRIMERA AFICIONADO');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (11, 2, 'COPA DE AFICIONADOS RFFM TEMP 24/25');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (12, 2, 'SEGUNDA AFICIONADO');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (13, 3, 'NACIONAL JUVENIL');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (14, 3, 'FINAL CAMPEON PRIMERA DIVISION AUTONOMICA JUVENIL');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (15, 3, 'PRIMERA DIVISION AUTONOMICA JUVENIL');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (16, 3, 'PREFERENTE JUVENIL');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (17, 3, 'PRIMERA JUVENIL');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (18, 3, 'SEGUNDA JUVENIL');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (19, 4, 'SUPERLIGA CADETE');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (20, 4, 'DIVISION DE HONOR CADETE');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (21, 4, 'PRIMERA DIVISION AUTONOMICA CADETE');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (22, 4, 'PREFERENTE CADETE');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (23, 4, 'PRIMERA CADETE');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (24, 4, 'SEGUNDA CADETE');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (25, 5, 'SUPERLIGA INFANTIL');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (26, 5, 'DIVISION DE HONOR INFANTIL');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (27, 5, 'PRIMERA DIVISION AUTONOMICA INFANTIL');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (28, 5, 'PREFERENTE INFANTIL');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (29, 5, 'PRIMERA INFANTIL');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (30, 5, 'SEGUNDA INFANTIL');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (31, 6, 'SUPERLIGA ALEVIN');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (32, 6, 'DIVISION DE HONOR ALEVIN');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (33, 6, 'PRIMERA DIVISION AUTONOMICA ALEVIN');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (34, 6, 'PREFERENTE ALEVIN');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (35, 6, 'PRIMERA ALEVIN');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (36, 7, 'VETERANOS MASCULINO F11');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (37, 7, 'PRIMERA DIVISION AUTONÓMICA FEMENINO');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (38, 7, 'PREFERENTE FUTBOL FEMENINO');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (39, 7, 'PRIMERA FUTBOL FEMENINO');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (40, 7, 'PRIMERA DIVISION AUTONOMICA FEMENINO JUVENIL');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (41, 7, 'PREFERENTE FEMENINO JUVENIL');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (42, 7, 'PRIMERA FEMENINO JUVENIL');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (43, 7, 'PRIMERA DIVISION AUTONOMICA FEMENINO CADETE');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (44, 7, 'PREFERENTE FEMENINO CADETE');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (45, 7, 'PRIMERA FEMENINO CADETE');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (46, 8, 'CAMPEONATO NACIONAL DE SELECCIONES TERRITORIALES SUB-14');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (47, 8, 'CAMPEONATO NACIONAL DE SELECCIONES TERRITORIALES SUB-16');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (48, 8, 'CAMPEONATO UNIVERSITARIO FEMENINO');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (49, 8, 'CAMPEONATO UNIVERSITARIO MASCULINO');
    INSERT INTO app."Leagues" ("Id", "CategoryId", "Name")
    VALUES (50, 8, 'CAMPEONATO UNIVERSITARIO MASCULINO 2ª FASE F11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_Clubs_CountryId" ON app."Clubs" ("CountryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_ConfigurationCoach_CoachId" ON app."ConfigurationCoach" ("CoachId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_ConvocationHistories_ConvocationId" ON app."ConvocationHistories" ("ConvocationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_Convocations_AssistanceTypeId" ON app."Convocations" ("AssistanceTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_Convocations_ConvocationStatusId" ON app."Convocations" ("ConvocationStatusId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_Convocations_ExcuseTypeId" ON app."Convocations" ("ExcuseTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_Convocations_SportEventId" ON app."Convocations" ("SportEventId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_Convocations_TeamPlayerId" ON app."Convocations" ("TeamPlayerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_Leagues_CategoryId" ON app."Leagues" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_Materials_TaskTrainingBaseId" ON app."Materials" ("TaskTrainingBaseId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_PaymentPlans_Name" ON app."PaymentPlans" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Players_Alias" ON app."Players" ("Alias");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_Players_ClubId" ON app."Players" ("ClubId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Players_Id" ON app."Players" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_SessionTrainings_SportEventId" ON app."SessionTrainings" ("SportEventId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_SessionTrainings_TeamId" ON app."SessionTrainings" ("TeamId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_SportEvents_EventTypeId" ON app."SportEvents" ("EventTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_SportEvents_RivalId" ON app."SportEvents" ("RivalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_SportEvents_TeamId" ON app."SportEvents" ("TeamId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_SportEvents_TeamId1" ON app."SportEvents" ("TeamId1");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_Subscriptions_PaymentPlanId" ON app."Subscriptions" ("PaymentPlanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_Subscriptions_UserId" ON app."Subscriptions" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_TaskTrainings_SessionTrainingId" ON app."TaskTrainings" ("SessionTrainingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_TeamPlayerFamilies_TeamPlayerId" ON app."TeamPlayerFamilies" ("TeamPlayerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_TeamPlayers_PlayerId" ON app."TeamPlayers" ("PlayerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_TeamPlayers_TeamId" ON app."TeamPlayers" ("TeamId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_Teams_CategoryId" ON app."Teams" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_Teams_ClubId" ON app."Teams" ("ClubId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_Teams_LeagueId" ON app."Teams" ("LeagueId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_Teams_SeasonId" ON app."Teams" ("SeasonId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_Technicals_TechnicalTypeId" ON app."Technicals" ("TechnicalTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_TrainingPointsReports_PlayerId" ON app."TrainingPointsReports" ("PlayerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_TrainingPointsReports_SeasonId" ON app."TrainingPointsReports" ("SeasonId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_UserClubs_ClubId" ON app."UserClubs" ("ClubId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    CREATE INDEX "IX_UserClubs_RoleId" ON app."UserClubs" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    PERFORM setval(
        pg_get_serial_sequence('app."AssistanceTypes"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM app."AssistanceTypes") + 1,
            nextval(pg_get_serial_sequence('app."AssistanceTypes"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('app."Categories"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM app."Categories") + 1,
            nextval(pg_get_serial_sequence('app."Categories"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('app."ConvocationStatuses"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM app."ConvocationStatuses") + 1,
            nextval(pg_get_serial_sequence('app."ConvocationStatuses"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('app."Countries"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM app."Countries") + 1,
            nextval(pg_get_serial_sequence('app."Countries"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('app."DemarcationMaster"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM app."DemarcationMaster") + 1,
            nextval(pg_get_serial_sequence('app."DemarcationMaster"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('app."ExcuseTypes"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM app."ExcuseTypes") + 1,
            nextval(pg_get_serial_sequence('app."ExcuseTypes"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('app."Materials"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM app."Materials") + 1,
            nextval(pg_get_serial_sequence('app."Materials"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('app."Memberships"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM app."Memberships") + 1,
            nextval(pg_get_serial_sequence('app."Memberships"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('app."PlayTypes"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM app."PlayTypes") + 1,
            nextval(pg_get_serial_sequence('app."PlayTypes"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('app."PointsTypes"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM app."PointsTypes") + 1,
            nextval(pg_get_serial_sequence('app."PointsTypes"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('app."SportEventTypes"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM app."SportEventTypes") + 1,
            nextval(pg_get_serial_sequence('app."SportEventTypes"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('app."TacticalGoals"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM app."TacticalGoals") + 1,
            nextval(pg_get_serial_sequence('app."TacticalGoals"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('app."TechnicalGoals"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM app."TechnicalGoals") + 1,
            nextval(pg_get_serial_sequence('app."TechnicalGoals"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('app."TechnicalTypes"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM app."TechnicalTypes") + 1,
            nextval(pg_get_serial_sequence('app."TechnicalTypes"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('app."Leagues"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM app."Leagues") + 1,
            nextval(pg_get_serial_sequence('app."Leagues"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316173356_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260316173356_InitialCreate', '9.0.6');
    END IF;
END $EF$;

-- Migration: 20260502152751_AddUserProfile
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502152751_AddUserProfile') THEN
    CREATE TABLE app."UserProfiles" (
        "Id" text NOT NULL,
        "ApplicationUserId" text NOT NULL,
        "RoleName" text NOT NULL,
        "PlayerId" text,
        "TeamId" text,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
        CONSTRAINT "PK_UserProfiles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502152751_AddUserProfile') THEN
    CREATE UNIQUE INDEX "IX_UserProfiles_ApplicationUserId" ON app."UserProfiles" ("ApplicationUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502152751_AddUserProfile') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260502152751_AddUserProfile', '9.0.6');
    END IF;
END $EF$;
COMMIT;

