export type CategoryKey = "physical" | "technical" | "tactical" | "competitiveness";

export type ConceptLevel = {
  level: number;
  concept: string;
};

export type CharacteristicDef = {
  key: string;
  label: string;
  categoryKey: CategoryKey;
  isGoalkeeper: boolean;
  levels: ConceptLevel[];
};

// ---------------------------------------------------------------------------
// FIELD PLAYER CHARACTERISTICS (isGoalkeeper: false)
// ---------------------------------------------------------------------------

const FIELD_PHYSICAL: CharacteristicDef[] = [
  {
    key: "physicalSpeed",
    label: "Velocidad",
    categoryKey: "physical",
    isGoalkeeper: false,
    levels: [
      { level: 1,  concept: "Muy lento — no puede seguir el ritmo del juego" },
      { level: 2,  concept: "Lento — pierde metros constantemente con los rivales" },
      { level: 3,  concept: "Por debajo de la media — dificultades para acompañar el juego rápido" },
      { level: 4,  concept: "Algo lento — no logra sacar ventaja con el físico" },
      { level: 5,  concept: "Correcto — velocidad suficiente para competir a este nivel" },
      { level: 6,  concept: "Ágil — reacciona y se mueve bien en los momentos clave" },
      { level: 7,  concept: "Veloz — supera a la mayoría de rivales en distancias cortas" },
      { level: 8,  concept: "Rápido — genera peligro con su aceleración y llegada" },
      { level: 9,  concept: "Muy rápido — diferencial, casi imbatible en carrera" },
      { level: 10, concept: "Explosivo — velocidad élite, referente indiscutible en el equipo" },
    ],
  },
  {
    key: "physicalEndurance",
    label: "Resistencia",
    categoryKey: "physical",
    isGoalkeeper: false,
    levels: [
      { level: 1,  concept: "Sin fondo — se agota en los primeros minutos" },
      { level: 2,  concept: "Muy poca resistencia — rinde solo en ráfagas cortas" },
      { level: 3,  concept: "Resistencia baja — declive físico notorio antes del descanso" },
      { level: 4,  concept: "Resistencia limitada — segundo tiempo con claro descenso" },
      { level: 5,  concept: "Resistencia normal — completa partidos sin problemas graves" },
      { level: 6,  concept: "Buena resistencia — mantiene intensidad en el tramo final" },
      { level: 7,  concept: "Alta resistencia — activo y disponible durante todo el partido" },
      { level: 8,  concept: "Muy buena resistencia — motor constante incluso en la prórroga" },
      { level: 9,  concept: "Fondo físico élite — el nivel de intensidad no decae en ningún momento" },
      { level: 10, concept: "Resistencia excepcional — referente de sacrificio físico en el grupo" },
    ],
  },
  {
    key: "physicalStrength",
    label: "Fuerza",
    categoryKey: "physical",
    isGoalkeeper: false,
    levels: [
      { level: 1,  concept: "Sin fuerza — pierde todos los duelos físicos" },
      { level: 2,  concept: "Muy débil — cedido en casi cualquier contacto" },
      { level: 3,  concept: "Por debajo de la media — superable físicamente sin esfuerzo" },
      { level: 4,  concept: "Algo débil — no impone su físico en el juego" },
      { level: 5,  concept: "Correcto — compite en duelos físicos sin desventaja clara" },
      { level: 6,  concept: "Fuerte — gana la mayoría de los choques directos" },
      { level: 7,  concept: "Muy fuerte — impone su físico de forma habitual" },
      { level: 8,  concept: "Poderoso — referente en duelos cuerpo a cuerpo" },
      { level: 9,  concept: "Dominante — difícilmente cedido en cualquier contacto" },
      { level: 10, concept: "Excepcional — físicamente inigualable en su categoría" },
    ],
  },
];

const FIELD_TECHNICAL: CharacteristicDef[] = [
  {
    key: "technicalDribbling",
    label: "Regate",
    categoryKey: "technical",
    isGoalkeeper: false,
    levels: [
      { level: 1,  concept: "Sin habilidad — pierde el balón al primer contacto con presión" },
      { level: 2,  concept: "Muy pobre — apenas puede progresar con el balón ante oposición" },
      { level: 3,  concept: "Básico — solo realiza regates simples en espacios amplios" },
      { level: 4,  concept: "Limitado — superable fácilmente ante marcaje cercano" },
      { level: 5,  concept: "Correcto — supera rivales en situaciones favorables" },
      { level: 6,  concept: "Hábil — conduce con confianza y supera con frecuencia" },
      { level: 7,  concept: "Buen regateador — soluciona bien el 1vs1 a ritmo alto" },
      { level: 8,  concept: "Habilidoso — supera rivales en espacios reducidos con facilidad" },
      { level: 9,  concept: "Desequilibrante — genera peligro constante con el regate" },
      { level: 10, concept: "Excepcional — el regate es su arma principal, casi imparable" },
    ],
  },
  {
    key: "technicalPassing",
    label: "Pase",
    categoryKey: "technical",
    isGoalkeeper: false,
    levels: [
      { level: 1,  concept: "Muy deficiente — pierde el balón en casi todos los envíos" },
      { level: 2,  concept: "Pobre — errores frecuentes incluso en pases cortos" },
      { level: 3,  concept: "Básico — acierta solo en pases simples sin presión" },
      { level: 4,  concept: "Limitado — dificultades ante pases medios o con presión" },
      { level: 5,  concept: "Correcto — pase simple y fiable sin grandes ambiciones" },
      { level: 6,  concept: "Preciso — buena circulación, acertado en el pase a un toque" },
      { level: 7,  concept: "Buen pasador — variedad de envíos, juego vertical con criterio" },
      { level: 8,  concept: "Excelente — filtra pases entre líneas con regularidad" },
      { level: 9,  concept: "Director — organiza el juego del equipo con su distribución" },
      { level: 10, concept: "Excepcional — pase filtrado y preciso en cualquier circunstancia" },
    ],
  },
  {
    key: "technicalControl",
    label: "Conducción",
    categoryKey: "technical",
    isGoalkeeper: false,
    levels: [
      { level: 1,  concept: "Descontrolado — pierde el balón al conducir bajo presión mínima" },
      { level: 2,  concept: "Muy pobre — el balón se le va con frecuencia sin oposición" },
      { level: 3,  concept: "Básico — conduce solo en espacios amplios y sin presión" },
      { level: 4,  concept: "Limitado — poco limpio en la conducción a ritmo alto" },
      { level: 5,  concept: "Correcto — conduce bien en zonas sin presión" },
      { level: 6,  concept: "Limpio — buen control orientado, conduce con fluidez" },
      { level: 7,  concept: "Fiable — muy seguro con el balón ante presión moderada" },
      { level: 8,  concept: "Técnico — conduce en espacios reducidos con soltura" },
      { level: 9,  concept: "Excelente — control orientado preciso, muy difícil de robar" },
      { level: 10, concept: "Excepcional — dominio absoluto del balón en cualquier situación" },
    ],
  },
  {
    key: "technicalShooting",
    label: "Tiro",
    categoryKey: "technical",
    isGoalkeeper: false,
    levels: [
      { level: 1,  concept: "Sin disparo — muy raramente acierta a portería" },
      { level: 2,  concept: "Muy pobre — carece de potencia o dirección en el remate" },
      { level: 3,  concept: "Básico — solo marca en situaciones muy favorables" },
      { level: 4,  concept: "Limitado — no finaliza bien sin tiempo y espacio" },
      { level: 5,  concept: "Correcto — remata con criterio cuando la ocasión es clara" },
      { level: 6,  concept: "Buen finalizador — preciso en el remate dentro del área" },
      { level: 7,  concept: "Goleador — acumula llegadas y transforma con regularidad" },
      { level: 8,  concept: "Gran rematador — dispara con potencia y precisión desde cualquier ángulo" },
      { level: 9,  concept: "Letal — resuelve situaciones difíciles con eficacia" },
      { level: 10, concept: "Excepcional — referente goleador, convierte casi todo" },
    ],
  },
  {
    key: "technicalTackling",
    label: "Entradas",
    categoryKey: "technical",
    isGoalkeeper: false,
    levels: [
      { level: 1,  concept: "Muy pobre — raramente recupera el balón en la entrada" },
      { level: 2,  concept: "Deficiente — frecuentes faltas o pérdidas al intentar robar" },
      { level: 3,  concept: "Básico — solo intenta entradas muy favorables" },
      { level: 4,  concept: "Limitado — irregular, mezcla aciertos con errores" },
      { level: 5,  concept: "Correcto — entrada limpia cuando el momento es adecuado" },
      { level: 6,  concept: "Buen defensor — entra con decisión y buen timing" },
      { level: 7,  concept: "Contundente — recupera habitualmente, limpio en el lanzamiento" },
      { level: 8,  concept: "Muy efectivo — referente en la recuperación por la entrada" },
      { level: 9,  concept: "Dominante — gana casi todos los duelos de entrada" },
      { level: 10, concept: "Excepcional — entradas de élite, fuerza y timing perfecto" },
    ],
  },
  {
    key: "technicalInterceptions",
    label: "Intercepciones",
    categoryKey: "technical",
    isGoalkeeper: false,
    levels: [
      { level: 1,  concept: "Nula anticipación — no intercepta ni en pases obvios" },
      { level: 2,  concept: "Muy pobre — raramente se interpone en las líneas de pase" },
      { level: 3,  concept: "Básico — solo corta pases directos a su lado" },
      { level: 4,  concept: "Limitado — reactivo, tarde en la mayoría de situaciones" },
      { level: 5,  concept: "Correcto — corta algunos pases con criterio posicional" },
      { level: 6,  concept: "Atento — lectura razonable para anticiparse al rival" },
      { level: 7,  concept: "Buen interceptor — corta líneas de pase con regularidad" },
      { level: 8,  concept: "Muy efectivo — anticipa con frecuencia y limpia el juego" },
      { level: 9,  concept: "Excelente — gran capacidad de lectura y posicionamiento" },
      { level: 10, concept: "Excepcional — interceptor de élite, corta constantemente el juego rival" },
    ],
  },
  {
    key: "technicalHeading",
    label: "Cabeceo",
    categoryKey: "technical",
    isGoalkeeper: false,
    levels: [
      { level: 1,  concept: "Muy pobre — evita el juego aéreo o siempre pierde" },
      { level: 2,  concept: "Deficiente — casi nunca gana en el salto" },
      { level: 3,  concept: "Básico — solo remata en situaciones muy favorables" },
      { level: 4,  concept: "Limitado — débil en la disputa aérea bajo presión" },
      { level: 5,  concept: "Correcto — competitivo en el juego aéreo puntualmente" },
      { level: 6,  concept: "Aéreo — gana duelos aéreos con cierta regularidad" },
      { level: 7,  concept: "Poderoso — referente del equipo en el juego aéreo" },
      { level: 8,  concept: "Gran rematador de cabeza — eficaz en área propia y contraria" },
      { level: 9,  concept: "Dominante en el aire — muy difícil de batir en el salto" },
      { level: 10, concept: "Excepcional — referente aéreo, gana casi todos los duelos" },
    ],
  },
];

const FIELD_TACTICAL: CharacteristicDef[] = [
  {
    key: "tacticalDefensiveAwareness",
    label: "Vigilancias defensivas",
    categoryKey: "tactical",
    isGoalkeeper: false,
    levels: [
      { level: 1,  concept: "Sin vigilancia — siempre desplazado fuera de su zona de cobertura" },
      { level: 2,  concept: "Muy pobre — no cubre los espacios defensivos básicos" },
      { level: 3,  concept: "Básico — solo vigila al rival directo, descuida el espacio" },
      { level: 4,  concept: "Limitado — vigilancias inconsistentes según el momento" },
      { level: 5,  concept: "Correcto — cubre su zona de responsabilidad defensiva" },
      { level: 6,  concept: "Atento — mantiene vigilancias y detecta movimientos clave" },
      { level: 7,  concept: "Organizado — muy activo en la cobertura y vigilancias" },
      { level: 8,  concept: "Excelente — anticipa movimientos y cierra bien los espacios" },
      { level: 9,  concept: "Gran lectura — organizador de la línea defensiva" },
      { level: 10, concept: "Excepcional — defensa completa, referente en lectura de juego" },
    ],
  },
  {
    key: "tacticalMarking",
    label: "Marcaje",
    categoryKey: "tactical",
    isGoalkeeper: false,
    levels: [
      { level: 1,  concept: "Sin marcaje — el rival siempre libre para recibir" },
      { level: 2,  concept: "Muy pobre — pierde al rival en el 90% de las situaciones" },
      { level: 3,  concept: "Básico — marque solo cuando el rival está a su lado" },
      { level: 4,  concept: "Limitado — marcaje inconsistente, pierde posición frecuentemente" },
      { level: 5,  concept: "Correcto — mantiene el marcaje en situaciones normales" },
      { level: 6,  concept: "Atento — sigue al rival con criterio, buen seguimiento" },
      { level: 7,  concept: "Consistente — el rival raramente recibe cómodo a su lado" },
      { level: 8,  concept: "Excelente — reduce notoriamente el impacto del rival" },
      { level: 9,  concept: "Gran marcador — el rival raramente influye cuando le marca" },
      { level: 10, concept: "Excepcional — anula al rival de forma sistemática" },
    ],
  },
  {
    key: "tacticalTrackBack",
    label: "Repliegue",
    categoryKey: "tactical",
    isGoalkeeper: false,
    levels: [
      { level: 1,  concept: "No repliega — se queda arriba siempre" },
      { level: 2,  concept: "Muy pobre — raramente ayuda en el repliegue" },
      { level: 3,  concept: "Básico — vuelve solo cuando el equipo está en peligro claro" },
      { level: 4,  concept: "Limitado — repliegue lento e irregular" },
      { level: 5,  concept: "Correcto — repliega en la mayoría de transiciones" },
      { level: 6,  concept: "Activo — esfuerzo en el repliegue para cubrir posiciones" },
      { level: 7,  concept: "Constante — siempre disponible en el repliegue defensivo" },
      { level: 8,  concept: "Muy rápido — cierra espacios con rapidez en el repliegue" },
      { level: 9,  concept: "Excelente — motor del repliegue colectivo del equipo" },
      { level: 10, concept: "Excepcional — repliegue total, equilibrio perfecto en el equipo" },
    ],
  },
  {
    key: "tacticalPressing",
    label: "Pressing",
    categoryKey: "tactical",
    isGoalkeeper: false,
    levels: [
      { level: 1,  concept: "Sin pressing — no presiona al rival en ninguna situación" },
      { level: 2,  concept: "Muy pobre — pressing pasivo, sin efectividad" },
      { level: 3,  concept: "Básico — pressing solo en su zona próxima" },
      { level: 4,  concept: "Limitado — esfuerzo irregular en la presión" },
      { level: 5,  concept: "Correcto — presiona cuando el bloque lo pide" },
      { level: 6,  concept: "Activo — participación habitual en el pressing colectivo" },
      { level: 7,  concept: "Muy activo — genera pressing efectivo con frecuencia" },
      { level: 8,  concept: "Intenso — clave en la recuperación alta del equipo" },
      { level: 9,  concept: "Élite — motor del pressing, fuerza recuperaciones constantes" },
      { level: 10, concept: "Excepcional — maestro del pressing, marca el ritmo del bloque" },
    ],
  },
  {
    key: "tacticalGeneratesAdvantage",
    label: "Genera ventaja en ataque",
    categoryKey: "tactical",
    isGoalkeeper: false,
    levels: [
      { level: 1,  concept: "Sin aporte — nunca genera situaciones favorables" },
      { level: 2,  concept: "Muy pobre — su juego no crea peligro al equipo rival" },
      { level: 3,  concept: "Básico — genera ventaja solo en situaciones muy favorables" },
      { level: 4,  concept: "Limitado — irregular, pocas situaciones provechosas" },
      { level: 5,  concept: "Correcto — aporta en situaciones de ataque sin exceso" },
      { level: 6,  concept: "Activo — genera situaciones de peligro con regularidad" },
      { level: 7,  concept: "Creativo — desequilibra y genera peligro habitualmente" },
      { level: 8,  concept: "Determinante — referente en la creación de juego" },
      { level: 9,  concept: "Clave — su participación aumenta notoriamente el peligro" },
      { level: 10, concept: "Excepcional — generador de ventajas continuo, decisivo" },
    ],
  },
  {
    key: "tacticalOffMovement",
    label: "Desmarque",
    categoryKey: "tactical",
    isGoalkeeper: false,
    levels: [
      { level: 1,  concept: "Sin desmarque — siempre parado o tapado por rivales" },
      { level: 2,  concept: "Muy pobre — no se ofrece ni busca espacios" },
      { level: 3,  concept: "Básico — solo se desmarca en espacios muy evidentes" },
      { level: 4,  concept: "Limitado — desmarques estáticos o sin recorrido" },
      { level: 5,  concept: "Correcto — se ofrece en momentos oportunos" },
      { level: 6,  concept: "Activo — buen movimiento sin balón para generar espacios" },
      { level: 7,  concept: "Inteligente — desmarques que crean peligro real" },
      { level: 8,  concept: "Excelente — creación constante de espacios para sí y compañeros" },
      { level: 9,  concept: "Muy inteligente — posicionamiento élite sin balón" },
      { level: 10, concept: "Excepcional — referente en el movimiento sin balón" },
    ],
  },
  {
    key: "tacticalBeatsOpponents",
    label: "Supera rivales",
    categoryKey: "tactical",
    isGoalkeeper: false,
    levels: [
      { level: 1,  concept: "No supera — siempre neutralizado por el rival" },
      { level: 2,  concept: "Muy pobre — raramente avanza o supera a un rival" },
      { level: 3,  concept: "Básico — solo supera cuando tiene gran ventaja" },
      { level: 4,  concept: "Limitado — supera en pocas ocasiones y con dificultad" },
      { level: 5,  concept: "Correcto — supera en situaciones favorables" },
      { level: 6,  concept: "Efectivo — supera rivales con regularidad" },
      { level: 7,  concept: "Desequilibrante — habitual en la superación de rivales" },
      { level: 8,  concept: "Peligroso — genera ventajas en la mayoría de situaciones" },
      { level: 9,  concept: "Imparable — difícilmente neutralizado cuando entra en juego" },
      { level: 10, concept: "Excepcional — referente en la superación de rivales" },
    ],
  },
  {
    key: "tacticalAttackParticipation",
    label: "Participación en ataque",
    categoryKey: "tactical",
    isGoalkeeper: false,
    levels: [
      { level: 1,  concept: "Sin participación — ausente del juego ofensivo" },
      { level: 2,  concept: "Muy pobre — raramente aparece en zonas de ataque" },
      { level: 3,  concept: "Básico — aparece puntualmente en ataque" },
      { level: 4,  concept: "Limitado — participación en ataque baja" },
      { level: 5,  concept: "Correcto — aporta en el juego ofensivo sin destacar" },
      { level: 6,  concept: "Activo — buena participación en el ataque del equipo" },
      { level: 7,  concept: "Dinámico — presente en muchas situaciones de ataque" },
      { level: 8,  concept: "Muy activo — jugador de ataque completo, desequilibra con frecuencia" },
      { level: 9,  concept: "Determinante — su participación genera peligro constante" },
      { level: 10, concept: "Excepcional — referente ofensivo, presencia constante en el ataque" },
    ],
  },
];

const FIELD_COMPETITIVENESS: CharacteristicDef[] = [
  {
    key: "competDuelWinning",
    label: "Ganador de duelos",
    categoryKey: "competitiveness",
    isGoalkeeper: false,
    levels: [
      { level: 1,  concept: "Evita los duelos — no compite físicamente" },
      { level: 2,  concept: "Pierde la mayoría — muy escasa efectividad en los duelos" },
      { level: 3,  concept: "Por debajo de la media — pierde más de lo que gana" },
      { level: 4,  concept: "Irregular — alterna victorias y derrotas sin consistencia" },
      { level: 5,  concept: "Correcto — gana aproximadamente la mitad de los duelos" },
      { level: 6,  concept: "Competidor — gana la mayoría de los duelos directos" },
      { level: 7,  concept: "Fuerte — muy difícil de superar en los duelos" },
      { level: 8,  concept: "Ganador habitual — referente del equipo en los duelos" },
      { level: 9,  concept: "Dominante — casi siempre sale victorioso del duelo" },
      { level: 10, concept: "Excepcional — gana todos los duelos, referente físico" },
    ],
  },
  {
    key: "competLooseBalls",
    label: "Bal. divididos disp.",
    categoryKey: "competitiveness",
    isGoalkeeper: false,
    levels: [
      { level: 1,  concept: "Sin intensidad — siempre cede los balones divididos" },
      { level: 2,  concept: "Muy pobre — raramente compite por el balón dividido" },
      { level: 3,  concept: "Por debajo de la media — poca efectividad en los segundos balones" },
      { level: 4,  concept: "Irregular — disputa sin mucha consistencia" },
      { level: 5,  concept: "Correcto — compite en los balones divididos" },
      { level: 6,  concept: "Activo — lucha con constancia por los balones divididos" },
      { level: 7,  concept: "Muy activo — referente en la disputa de segundos balones" },
      { level: 8,  concept: "Dominante — gana la mayoría de los balones divididos" },
      { level: 9,  concept: "Excelente — motor del equipo en la disputa de balones" },
      { level: 10, concept: "Excepcional — referente absoluto en la pelea por el balón" },
    ],
  },
  {
    key: "competRecoveries",
    label: "Recuperaciones",
    categoryKey: "competitiveness",
    isGoalkeeper: false,
    levels: [
      { level: 1,  concept: "Sin recuperaciones — no recupera balones" },
      { level: 2,  concept: "Muy pobre — raramente recupera balones para el equipo" },
      { level: 3,  concept: "Por debajo de la media — poca efectividad en recuperar" },
      { level: 4,  concept: "Irregular — recupera de vez en cuando" },
      { level: 5,  concept: "Correcto — recupera balones en situaciones favorables" },
      { level: 6,  concept: "Activo — recuperaciones habituales durante el partido" },
      { level: 7,  concept: "Muy activo — referente en la recuperación de balones" },
      { level: 8,  concept: "Excelente — generador de recuperaciones para el equipo" },
      { level: 9,  concept: "Élite — motor de las recuperaciones del equipo" },
      { level: 10, concept: "Excepcional — referente absoluto en la recuperación del balón" },
    ],
  },
  {
    key: "competDecisiveActions",
    label: "Acciones decisivas",
    categoryKey: "competitiveness",
    isGoalkeeper: false,
    levels: [
      { level: 1,  concept: "Sin aportación — nunca decide partidos ni situaciones clave" },
      { level: 2,  concept: "Muy pobre — raramente toma el partido a su cargo" },
      { level: 3,  concept: "Básico — solo en situaciones muy sencillas" },
      { level: 4,  concept: "Limitado — poca efectividad en los momentos decisivos" },
      { level: 5,  concept: "Correcto — aporta en situaciones normales del partido" },
      { level: 6,  concept: "Efectivo — interviene con acierto en momentos clave" },
      { level: 7,  concept: "Importante — presencia habitual en las acciones más decisivas" },
      { level: 8,  concept: "Muy importante — referente del equipo cuando el partido lo exige" },
      { level: 9,  concept: "Determinante — define partidos de forma habitual" },
      { level: 10, concept: "Excepcional — referente en los momentos decisivos del equipo" },
    ],
  },
  {
    key: "competResponsibility",
    label: "Asume responsabilidades",
    categoryKey: "competitiveness",
    isGoalkeeper: false,
    levels: [
      { level: 1,  concept: "Evita las responsabilidades — nunca toma la iniciativa" },
      { level: 2,  concept: "Muy pobre — cede siempre la responsabilidad a compañeros" },
      { level: 3,  concept: "Básico — asume solo cuando es inevitable" },
      { level: 4,  concept: "Limitado — falta constancia en asumir el protagonismo" },
      { level: 5,  concept: "Correcto — asume su parte de responsabilidad en el grupo" },
      { level: 6,  concept: "Activo — toma la iniciativa con frecuencia" },
      { level: 7,  concept: "Referente — asume responsabilidades en los momentos importantes" },
      { level: 8,  concept: "Líder — se hace cargo del equipo cuando lo necesita" },
      { level: 9,  concept: "Muy líder — referente indiscutible en el vestuario" },
      { level: 10, concept: "Excepcional — líder nato, asume toda la responsabilidad del grupo" },
    ],
  },
  {
    key: "competConstantEffort",
    label: "Esfuerzo constante",
    categoryKey: "competitiveness",
    isGoalkeeper: false,
    levels: [
      { level: 1,  concept: "Sin esfuerzo — no trabaja por el equipo" },
      { level: 2,  concept: "Muy pobre — solo rinde en destellos cortos" },
      { level: 3,  concept: "Por debajo de la media — esfuerzo muy inconstante" },
      { level: 4,  concept: "Irregular — alterna momentos de esfuerzo con pasividad" },
      { level: 5,  concept: "Correcto — esfuerzo sostenido a lo largo del partido" },
      { level: 6,  concept: "Trabajador — esfuerzo constante que el equipo nota" },
      { level: 7,  concept: "Muy trabajador — entrega total en cada acción" },
      { level: 8,  concept: "Incansable — motor del equipo en esfuerzo y actitud" },
      { level: 9,  concept: "Ejemplar — referente de esfuerzo para el grupo" },
      { level: 10, concept: "Excepcional — máximo esfuerzo en cada partido, referente absoluto" },
    ],
  },
];

export const FIELD_PLAYER_CHARACTERISTICS: CharacteristicDef[] = [
  ...FIELD_PHYSICAL,
  ...FIELD_TECHNICAL,
  ...FIELD_TACTICAL,
  ...FIELD_COMPETITIVENESS,
];

// ---------------------------------------------------------------------------
// GOALKEEPER CHARACTERISTICS (isGoalkeeper: true)
// ---------------------------------------------------------------------------

const KEEPER_PHYSICAL: CharacteristicDef[] = [
  {
    key: "keeperReactionSpeed",
    label: "Reflejos / vel. reacción",
    categoryKey: "physical",
    isGoalkeeper: true,
    levels: [
      { level: 1,  concept: "Sin reflejos — no reacciona a tiempo ante los disparos" },
      { level: 2,  concept: "Muy lento — reacciona tarde en la mayoría de situaciones" },
      { level: 3,  concept: "Por debajo de la media — reflejos lentos en disparos rápidos" },
      { level: 4,  concept: "Irregular — reacciona bien solo en algunas situaciones" },
      { level: 5,  concept: "Correcto — reacciona bien ante la mayoría de disparos directos" },
      { level: 6,  concept: "Ágil — buenas reacciones en disparos desde cerca" },
      { level: 7,  concept: "Rápido — destaca en las paradas de reacción rápida" },
      { level: 8,  concept: "Muy rápido — reflejos por encima de la media, muy difícil de batir" },
      { level: 9,  concept: "Excepcional — reflejos casi felinos, para todo" },
      { level: 10, concept: "Élite — reflejos extraordinarios, referente en el puesto" },
    ],
  },
  {
    key: "keeperAgility",
    label: "Agilidad",
    categoryKey: "physical",
    isGoalkeeper: true,
    levels: [
      { level: 1,  concept: "Torpe — sin agilidad para cubrir los postes" },
      { level: 2,  concept: "Muy poca agilidad — desplazamiento lento y torpe" },
      { level: 3,  concept: "Por debajo de la media — limitaciones evidentes en agilidad" },
      { level: 4,  concept: "Limitado — movimientos lentos entre los postes" },
      { level: 5,  concept: "Correcto — agilidad suficiente para competir en este nivel" },
      { level: 6,  concept: "Ágil — buenos desplazamientos bajo palos" },
      { level: 7,  concept: "Muy ágil — se mueve con soltura en cualquier situación" },
      { level: 8,  concept: "Excelente — agilidad que marca diferencia en el puesto" },
      { level: 9,  concept: "Atlético — referente de agilidad en su posición" },
      { level: 10, concept: "Excepcional — agilidad élite, supera casi cualquier situación" },
    ],
  },
  {
    key: "keeperJumpPower",
    label: "Potencia de salto",
    categoryKey: "physical",
    isGoalkeeper: true,
    levels: [
      { level: 1,  concept: "Sin salto — no puede competir en el juego aéreo" },
      { level: 2,  concept: "Muy pobre — salto irrelevante en los despejes" },
      { level: 3,  concept: "Por debajo de la media — limitaciones en el juego aéreo" },
      { level: 4,  concept: "Limitado — no gana los duelos aéreos importantes" },
      { level: 5,  concept: "Correcto — puede competir en el juego aéreo básico" },
      { level: 6,  concept: "Bueno — gana la mayoría de los duelos aéreos" },
      { level: 7,  concept: "Potente — salto que marca diferencia en el área" },
      { level: 8,  concept: "Excelente — muy difícil de batir en el juego aéreo" },
      { level: 9,  concept: "Excepcional — referente en el salto dentro del área" },
      { level: 10, concept: "Élite — dominio absoluto del juego aéreo" },
    ],
  },
  {
    key: "keeperStrength",
    label: "Fuerza / cuerpo a cuerpo",
    categoryKey: "physical",
    isGoalkeeper: true,
    levels: [
      { level: 1,  concept: "Sin fuerza — pierde todos los choques físicos" },
      { level: 2,  concept: "Muy débil — no puede aguantar la presión del delantero" },
      { level: 3,  concept: "Por debajo de la media — cedido con facilidad en el uno contra uno" },
      { level: 4,  concept: "Limitado — fuerza insuficiente en situaciones de presión" },
      { level: 5,  concept: "Correcto — compite físicamente en las situaciones habituales" },
      { level: 6,  concept: "Fuerte — impone su presencia física" },
      { level: 7,  concept: "Muy fuerte — referente en la disputa cuerpo a cuerpo" },
      { level: 8,  concept: "Poderoso — domina la mayoría de disputas físicas" },
      { level: 9,  concept: "Dominante — muy difícil de mover bajo palos" },
      { level: 10, concept: "Excepcional — fuerza élite, impone su físico siempre" },
    ],
  },
  {
    key: "keeperEndurance",
    label: "Resistencia / constancia",
    categoryKey: "physical",
    isGoalkeeper: true,
    levels: [
      { level: 1,  concept: "Sin resistencia — fatiga visible desde el inicio" },
      { level: 2,  concept: "Muy poca — solo rinde en ráfagas cortas" },
      { level: 3,  concept: "Por debajo de la media — declive claro en la segunda parte" },
      { level: 4,  concept: "Limitada — pérdida de concentración o intensidad notable" },
      { level: 5,  concept: "Correcto — completa los partidos sin problema grave" },
      { level: 6,  concept: "Constante — mantiene el nivel durante todo el partido" },
      { level: 7,  concept: "Alto — motor constante sin pérdida de concentración" },
      { level: 8,  concept: "Excelente — referente de constancia en el portero" },
      { level: 9,  concept: "Élite — nivel sostenido incluso en los momentos finales" },
      { level: 10, concept: "Excepcional — resistencia física y mental sin igual" },
    ],
  },
];

const KEEPER_TECHNICAL: CharacteristicDef[] = [
  {
    key: "keeperHandSecurity",
    label: "Blocaje / seguridad manos",
    categoryKey: "technical",
    isGoalkeeper: true,
    levels: [
      { level: 1,  concept: "Manos inseguras — suelta el balón casi siempre" },
      { level: 2,  concept: "Muy pobre — muchos rechaces y errores de agarre" },
      { level: 3,  concept: "Por debajo de la media — agarre poco fiable bajo presión" },
      { level: 4,  concept: "Limitado — rechaces frecuentes en los disparos sencillos" },
      { level: 5,  concept: "Correcto — agarre fiable en la mayoría de las situaciones" },
      { level: 6,  concept: "Seguro — blocaje limpio con frecuencia" },
      { level: 7,  concept: "Muy seguro — raramente suelta el balón en los disparos" },
      { level: 8,  concept: "Excelente — manos muy firmes, bloquea casi todo" },
      { level: 9,  concept: "Excepcional — pocas rechaces, inspira confianza" },
      { level: 10, concept: "Élite — seguridad absoluta en las manos" },
    ],
  },
  {
    key: "keeperSaves",
    label: "Paradas",
    categoryKey: "technical",
    isGoalkeeper: true,
    levels: [
      { level: 1,  concept: "Sin efectividad — encaja casi todos los disparos a puerta" },
      { level: 2,  concept: "Muy pobre — poca capacidad para detener los disparos" },
      { level: 3,  concept: "Por debajo de la media — encaja muchos goles evitables" },
      { level: 4,  concept: "Limitado — paradas solo en disparos poco colocados" },
      { level: 5,  concept: "Correcto — para los disparos que debería parar" },
      { level: 6,  concept: "Efectivo — destaca en algunas paradas importantes" },
      { level: 7,  concept: "Buen portero — paradas regulares de buen nivel" },
      { level: 8,  concept: "Gran portero — paradas muy importantes que dan puntos al equipo" },
      { level: 9,  concept: "Excepcional — referente de paradas en el equipo" },
      { level: 10, concept: "Élite — portero que gana partidos con sus paradas" },
    ],
  },
  {
    key: "keeperAerialPlay",
    label: "Juego aéreo",
    categoryKey: "technical",
    isGoalkeeper: true,
    levels: [
      { level: 1,  concept: "Sin dominio aéreo — nunca sale al balón colgado" },
      { level: 2,  concept: "Muy pobre — raramente tiene éxito en las salidas aéreas" },
      { level: 3,  concept: "Por debajo de la media — juego aéreo inseguro y limitado" },
      { level: 4,  concept: "Limitado — dudas frecuentes en las salidas a centros" },
      { level: 5,  concept: "Correcto — juego aéreo aceptable en situaciones favorables" },
      { level: 6,  concept: "Activo — sale con decisión en la mayoría de centros" },
      { level: 7,  concept: "Dominante — controla el área en el juego aéreo" },
      { level: 8,  concept: "Muy dominante — casi nunca duda en las salidas aéreas" },
      { level: 9,  concept: "Excepcional — referente en el control del área" },
      { level: 10, concept: "Élite — dominio total del juego aéreo, inspira seguridad" },
    ],
  },
  {
    key: "keeperHandDistribution",
    label: "Saques con mano",
    categoryKey: "technical",
    isGoalkeeper: true,
    levels: [
      { level: 1,  concept: "Sin distribución — saque con mano impreciso y corto" },
      { level: 2,  concept: "Muy pobre — raramente encuentra a un compañero" },
      { level: 3,  concept: "Por debajo de la media — saques poco precisos" },
      { level: 4,  concept: "Limitado — dificultades para variar el saque" },
      { level: 5,  concept: "Correcto — encuentra a un compañero en el saque habitual" },
      { level: 6,  concept: "Preciso — saque con mano con buena dirección" },
      { level: 7,  concept: "Muy preciso — lanza al hombre con regularidad" },
      { level: 8,  concept: "Excelente — inicia el juego con saque rápido y preciso" },
      { level: 9,  concept: "Excepcional — referente en la distribución con mano" },
      { level: 10, concept: "Élite — saques que transforman el juego del equipo" },
    ],
  },
  {
    key: "keeperKickDistribution",
    label: "Saques con pie",
    categoryKey: "technical",
    isGoalkeeper: true,
    levels: [
      { level: 1,  concept: "Sin distribución — saque con pie sin criterio ni precisión" },
      { level: 2,  concept: "Muy pobre — pierde casi siempre en el saque con pie" },
      { level: 3,  concept: "Por debajo de la media — patadas poco precisas y cortas" },
      { level: 4,  concept: "Limitado — poca variedad en el saque con pie" },
      { level: 5,  concept: "Correcto — saque con pie funcional, no pierde el balón" },
      { level: 6,  concept: "Preciso — buena distribución con el pie en jugadas directas" },
      { level: 7,  concept: "Muy preciso — encuentra a compañeros en larga distancia" },
      { level: 8,  concept: "Excelente — distribución de largo alcance con precisión" },
      { level: 9,  concept: "Excepcional — lanza el contraataque con el saque" },
      { level: 10, concept: "Élite — distribución élite, primer pase del equipo" },
    ],
  },
  {
    key: "keeperFirstTouch",
    label: "Control / primer toque",
    categoryKey: "technical",
    isGoalkeeper: true,
    levels: [
      { level: 1,  concept: "Sin primer toque — pierde el balón al primer contacto" },
      { level: 2,  concept: "Muy pobre — primer toque muy deficiente bajo presión" },
      { level: 3,  concept: "Por debajo de la media — control poco seguro en situaciones difíciles" },
      { level: 4,  concept: "Limitado — primer toque aceptable solo sin presión" },
      { level: 5,  concept: "Correcto — primer toque funcional en situaciones normales" },
      { level: 6,  concept: "Limpio — buen control orientado en el primer toque" },
      { level: 7,  concept: "Técnico — primer toque depurado para iniciar el juego" },
      { level: 8,  concept: "Excelente — control y distribución inmediata con fluidez" },
      { level: 9,  concept: "Excepcional — primer toque de élite, inicia el juego rápido" },
      { level: 10, concept: "Élite — primer toque extraordinario, elemento diferencial" },
    ],
  },
  {
    key: "keeperPlayUnderPressure",
    label: "Juego con pies a presión",
    categoryKey: "technical",
    isGoalkeeper: true,
    levels: [
      { level: 1,  concept: "Sin juego — pierde el balón siempre al presionarle" },
      { level: 2,  concept: "Muy pobre — muy nervioso, errores graves bajo presión" },
      { level: 3,  concept: "Por debajo de la media — dificultades claras cuando le presionan" },
      { level: 4,  concept: "Limitado — resuelve mal la presión frecuentemente" },
      { level: 5,  concept: "Correcto — juega bien con presión moderada" },
      { level: 6,  concept: "Calmado — resuelve bajo presión con eficacia" },
      { level: 7,  concept: "Técnico — supera el pressing con soltura" },
      { level: 8,  concept: "Excelente — referente en el juego bajo presión" },
      { level: 9,  concept: "Excepcional — muy difícil de presionar" },
      { level: 10, concept: "Élite — juego bajo presión de primer nivel, no comete errores" },
    ],
  },
];

const KEEPER_TACTICAL: CharacteristicDef[] = [
  {
    key: "keeperPositioning",
    label: "Colocación",
    categoryKey: "tactical",
    isGoalkeeper: true,
    levels: [
      { level: 1,  concept: "Mal colocado — posición deficiente en la mayoría de situaciones" },
      { level: 2,  concept: "Muy pobre — posición que facilita los goles al rival" },
      { level: 3,  concept: "Por debajo de la media — colocación irregular, deja espacios" },
      { level: 4,  concept: "Limitado — falta de ajuste en su posicionamiento" },
      { level: 5,  concept: "Correcto — colocación básica adecuada para este nivel" },
      { level: 6,  concept: "Bueno — buena posición en los diferentes tipos de remate" },
      { level: 7,  concept: "Muy bueno — posicionamiento preciso en casi todas las situaciones" },
      { level: 8,  concept: "Excelente — colocación que reduce el ángulo al máximo" },
      { level: 9,  concept: "Excepcional — posicionamiento de élite, difícil de batir" },
      { level: 10, concept: "Élite — referente en colocación, inspira confianza al equipo" },
    ],
  },
  {
    key: "keeperGameReading",
    label: "Lectura de jugadas",
    categoryKey: "tactical",
    isGoalkeeper: true,
    levels: [
      { level: 1,  concept: "Sin lectura — no anticipa las jugadas" },
      { level: 2,  concept: "Muy pobre — raramente lee el juego del rival" },
      { level: 3,  concept: "Por debajo de la media — lectura lenta o incorrecta frecuentemente" },
      { level: 4,  concept: "Limitado — anticipa solo las jugadas más evidentes" },
      { level: 5,  concept: "Correcto — lectura básica adecuada para competir" },
      { level: 6,  concept: "Atento — anticipa con regularidad las jugadas" },
      { level: 7,  concept: "Inteligente — buena lectura del juego en la mayoría de situaciones" },
      { level: 8,  concept: "Excelente — anticipa y posiciona al equipo con su lectura" },
      { level: 9,  concept: "Excepcional — lectura de juego de primer nivel" },
      { level: 10, concept: "Élite — referente en la lectura del juego en su área" },
    ],
  },
  {
    key: "keeperOneOnOne",
    label: "Uno contra uno",
    categoryKey: "tactical",
    isGoalkeeper: true,
    levels: [
      { level: 1,  concept: "Mal en el uno contra uno — siempre sale perdiendo" },
      { level: 2,  concept: "Muy pobre — gana muy raramente el uno contra uno" },
      { level: 3,  concept: "Por debajo de la media — situación muy desfavorable para él" },
      { level: 4,  concept: "Limitado — poca efectividad en el mano a mano" },
      { level: 5,  concept: "Correcto — puede competir en el uno contra uno" },
      { level: 6,  concept: "Efectivo — sale bien en muchas situaciones de uno contra uno" },
      { level: 7,  concept: "Bueno — reduce el espacio y el ángulo eficazmente" },
      { level: 8,  concept: "Excelente — el uno contra uno casi nunca resulta en gol" },
      { level: 9,  concept: "Excepcional — domina la situación en el mano a mano" },
      { level: 10, concept: "Élite — referente en el uno contra uno" },
    ],
  },
  {
    key: "keeperBackCoverage",
    label: "Cobertura de espalda",
    categoryKey: "tactical",
    isGoalkeeper: true,
    levels: [
      { level: 1,  concept: "Sin cobertura — no cubre los espacios a su espalda" },
      { level: 2,  concept: "Muy pobre — raramente sale a cubrir el pase a su espalda" },
      { level: 3,  concept: "Por debajo de la media — cobertura lenta y sin criterio" },
      { level: 4,  concept: "Limitado — solo cubre las más sencillas" },
      { level: 5,  concept: "Correcto — cubre su espalda en situaciones normales" },
      { level: 6,  concept: "Atento — sale con decisión a cubrir la espalda" },
      { level: 7,  concept: "Activo — cubre la espalda con eficacia y criterio" },
      { level: 8,  concept: "Excelente — muy seguro en los espacios a su espalda" },
      { level: 9,  concept: "Excepcional — lectura de la línea, elimina el peligro" },
      { level: 10, concept: "Élite — cobertura de espalda extraordinaria" },
    ],
  },
  {
    key: "keeperSallyTiming",
    label: "Timing de salidas",
    categoryKey: "tactical",
    isGoalkeeper: true,
    levels: [
      { level: 1,  concept: "Mal timing — salidas contraproducentes o siempre en duda" },
      { level: 2,  concept: "Muy pobre — raramente sale en el momento correcto" },
      { level: 3,  concept: "Por debajo de la media — salidas frecuentemente tardías o precipitadas" },
      { level: 4,  concept: "Limitado — dudas frecuentes en el momento de salir" },
      { level: 5,  concept: "Correcto — sale en el momento adecuado en situaciones claras" },
      { level: 6,  concept: "Decisivo — buen timing de salida en la mayoría de casos" },
      { level: 7,  concept: "Muy seguro — sale con confianza y en el momento idóneo" },
      { level: 8,  concept: "Excelente — timing de salida que despeja el peligro" },
      { level: 9,  concept: "Excepcional — referente en el timing de salidas" },
      { level: 10, concept: "Élite — salidas perfectamente medidas, anula los peligros" },
    ],
  },
  {
    key: "keeperBuildupPlay",
    label: "Salida de balón",
    categoryKey: "tactical",
    isGoalkeeper: true,
    levels: [
      { level: 1,  concept: "Sin juego de construcción — solo despeja sin criterio" },
      { level: 2,  concept: "Muy pobre — raramente inicia el juego organizado" },
      { level: 3,  concept: "Por debajo de la media — poca participación en el juego de salida" },
      { level: 4,  concept: "Limitado — solo juega hacia atrás de forma simple" },
      { level: 5,  concept: "Correcto — participa en el juego de salida sin exceso" },
      { level: 6,  concept: "Activo — buen inicio del juego con pie o mano" },
      { level: 7,  concept: "Técnico — clave en la construcción del equipo desde atrás" },
      { level: 8,  concept: "Excelente — primer pase del equipo, inicia las jugadas" },
      { level: 9,  concept: "Excepcional — portero-constructor, referente en el buildup" },
      { level: 10, concept: "Élite — elemento diferencial en el juego de salida del equipo" },
    ],
  },
  {
    key: "keeperDefensiveOrganization",
    label: "Orden defensivo",
    categoryKey: "tactical",
    isGoalkeeper: true,
    levels: [
      { level: 1,  concept: "Sin comunicación — no organiza ni habla con la defensa" },
      { level: 2,  concept: "Muy pobre — comunicación confusa o casi nula" },
      { level: 3,  concept: "Por debajo de la media — comunica solo en momentos evidentes" },
      { level: 4,  concept: "Limitado — falta consistencia en la organización defensiva" },
      { level: 5,  concept: "Correcto — comunica lo básico para organizar la línea" },
      { level: 6,  concept: "Activo — organiza la defensa con frecuencia" },
      { level: 7,  concept: "Muy activo — referente de la organización defensiva" },
      { level: 8,  concept: "Excelente — clave en la estructura defensiva del equipo" },
      { level: 9,  concept: "Excepcional — líder defensivo, organiza al equipo constantemente" },
      { level: 10, concept: "Élite — portero líder de la defensa, referente absoluto" },
    ],
  },
];

const KEEPER_COMPETITIVENESS: CharacteristicDef[] = [
  {
    key: "keeperValor",
    label: "Valentía",
    categoryKey: "competitiveness",
    isGoalkeeper: true,
    levels: [
      { level: 1,  concept: "Cobarde — evita los balones peligrosos" },
      { level: 2,  concept: "Muy pobre — raramente se lanza a situaciones de riesgo" },
      { level: 3,  concept: "Por debajo de la media — dudas frecuentes ante situaciones de riesgo" },
      { level: 4,  concept: "Limitado — valentía insuficiente en los momentos clave" },
      { level: 5,  concept: "Correcto — valentía adecuada para el nivel" },
      { level: 6,  concept: "Decidido — se lanza a situaciones de riesgo con decisión" },
      { level: 7,  concept: "Valiente — referente en la valentía dentro del área" },
      { level: 8,  concept: "Muy valiente — nunca duda ante situaciones peligrosas" },
      { level: 9,  concept: "Excepcional — valentía que inspira a la defensa" },
      { level: 10, concept: "Élite — valentía extraordinaria, eje del equipo defensivo" },
    ],
  },
  {
    key: "keeperConcentration",
    label: "Concentración",
    categoryKey: "competitiveness",
    isGoalkeeper: true,
    levels: [
      { level: 1,  concept: "Desconcentrado — errores frecuentes por falta de atención" },
      { level: 2,  concept: "Muy pobre — desconcentración visible durante el partido" },
      { level: 3,  concept: "Por debajo de la media — errores por falta de atención puntual" },
      { level: 4,  concept: "Limitado — dificultades para mantener la concentración" },
      { level: 5,  concept: "Correcto — concentración adecuada durante el partido" },
      { level: 6,  concept: "Atento — mantiene la concentración de forma habitual" },
      { level: 7,  concept: "Muy concentrado — raramente desconcentrado en el partido" },
      { level: 8,  concept: "Excelente — concentración sostenida en los momentos clave" },
      { level: 9,  concept: "Excepcional — referente de concentración en el equipo" },
      { level: 10, concept: "Élite — concentración máxima todo el partido, sin errores" },
    ],
  },
  {
    key: "keeperKeyMoments",
    label: "Momentos clave",
    categoryKey: "competitiveness",
    isGoalkeeper: true,
    levels: [
      { level: 1,  concept: "Flaquea — comete errores en los momentos más importantes" },
      { level: 2,  concept: "Muy pobre — raramente responde en los momentos decisivos" },
      { level: 3,  concept: "Por debajo de la media — inseguridad en momentos de presión" },
      { level: 4,  concept: "Limitado — inconsistente en las situaciones más importantes" },
      { level: 5,  concept: "Correcto — responde en la mayoría de momentos clave" },
      { level: 6,  concept: "Seguro — rinde bien en situaciones de presión" },
      { level: 7,  concept: "Fiable — referente de seguridad en los momentos clave" },
      { level: 8,  concept: "Excelente — decisivo en los momentos que el equipo más necesita" },
      { level: 9,  concept: "Excepcional — siempre en su mejor nivel cuando el partido lo exige" },
      { level: 10, concept: "Élite — referente indiscutible en los momentos decisivos" },
    ],
  },
  {
    key: "keeperErrorManagement",
    label: "Gestión del error",
    categoryKey: "competitiveness",
    isGoalkeeper: true,
    levels: [
      { level: 1,  concept: "Sin recuperación — el error le bloquea totalmente" },
      { level: 2,  concept: "Muy pobre — cuesta mucho recuperarse de un error" },
      { level: 3,  concept: "Por debajo de la media — el error afecta claramente su rendimiento" },
      { level: 4,  concept: "Limitado — recuperación lenta y visible" },
      { level: 5,  concept: "Correcto — gestiona los errores de forma suficiente" },
      { level: 6,  concept: "Resiliente — se recupera con rapidez de los errores" },
      { level: 7,  concept: "Muy resiliente — el error no afecta su rendimiento" },
      { level: 8,  concept: "Excelente — gestión del error ejemplar" },
      { level: 9,  concept: "Excepcional — referente en la gestión del error en el equipo" },
      { level: 10, concept: "Élite — mentalmente indestructible, el error le hace mejor" },
    ],
  },
  {
    key: "keeperResponsibility",
    label: "Responsabilidad",
    categoryKey: "competitiveness",
    isGoalkeeper: true,
    levels: [
      { level: 1,  concept: "Sin responsabilidad — nunca asume errores ni situaciones difíciles" },
      { level: 2,  concept: "Muy pobre — evita constantemente la responsabilidad" },
      { level: 3,  concept: "Por debajo de la media — falta de implicación en los momentos difíciles" },
      { level: 4,  concept: "Limitado — responsabilidad inconsistente" },
      { level: 5,  concept: "Correcto — asume su parte de responsabilidad" },
      { level: 6,  concept: "Responsable — se hace cargo de su juego y área" },
      { level: 7,  concept: "Muy responsable — referente de responsabilidad en el grupo" },
      { level: 8,  concept: "Excelente — asume la responsabilidad en los momentos clave" },
      { level: 9,  concept: "Excepcional — referente del equipo en responsabilidad" },
      { level: 10, concept: "Élite — portero líder que asume toda la responsabilidad" },
    ],
  },
  {
    key: "keeperConsistency",
    label: "Regularidad",
    categoryKey: "competitiveness",
    isGoalkeeper: true,
    levels: [
      { level: 1,  concept: "Muy irregular — nivel muy variable de partido en partido" },
      { level: 2,  concept: "Pobre — mucha inconsistencia en su rendimiento" },
      { level: 3,  concept: "Por debajo de la media — difícil de predecir su nivel" },
      { level: 4,  concept: "Irregular — alterna partidos buenos y malos sin patrón" },
      { level: 5,  concept: "Correcto — regularidad suficiente para competir" },
      { level: 6,  concept: "Regular — nivel sostenido habitualmente" },
      { level: 7,  concept: "Muy regular — rendimiento consistente en la mayoría de partidos" },
      { level: 8,  concept: "Excelente — referente de regularidad en el equipo" },
      { level: 9,  concept: "Excepcional — nivel muy alto sostenido durante toda la temporada" },
      { level: 10, concept: "Élite — regularidad extraordinaria, referente en el puesto" },
    ],
  },
];

export const GOALKEEPER_CHARACTERISTICS: CharacteristicDef[] = [
  ...KEEPER_PHYSICAL,
  ...KEEPER_TECHNICAL,
  ...KEEPER_TACTICAL,
  ...KEEPER_COMPETITIVENESS,
];

// ---------------------------------------------------------------------------
// Lookup helpers
// ---------------------------------------------------------------------------

/** All field-player + goalkeeper characteristics indexed by key */
const ALL_CHARACTERISTICS_MAP: Record<string, CharacteristicDef> = {};
for (const c of [...FIELD_PLAYER_CHARACTERISTICS, ...GOALKEEPER_CHARACTERISTICS]) {
  ALL_CHARACTERISTICS_MAP[c.key] = c;
}

export function getCharacteristicDef(key: string): CharacteristicDef | undefined {
  return ALL_CHARACTERISTICS_MAP[key];
}

export function getConceptForLevel(characteristicKey: string, level: number): string {
  const def = getCharacteristicDef(characteristicKey);
  if (!def) return `Nivel ${level}`;
  return def.levels.find((l) => l.level === level)?.concept ?? `Nivel ${level}`;
}

export function getCategoryLabel(categoryKey: CategoryKey): string {
  switch (categoryKey) {
    case "physical": return "Físico";
    case "technical": return "Técnica";
    case "tactical": return "Táctica";
    case "competitiveness": return "Competitividad";
  }
}
