// <auto-generated />
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using RFFM.Api.Infrastructure.Persistence;

#nullable disable

namespace RFFM.Api.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511204925_UpdateUserProfileDefaultsAndIndex")]
    partial class UpdateUserProfileDefaultsAndIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            var snapshot = new AppDbContextModelSnapshot();
            var buildModelMethod = typeof(AppDbContextModelSnapshot).GetMethod(
                "BuildModel",
                BindingFlags.Instance | BindingFlags.NonPublic);

            buildModelMethod!.Invoke(snapshot, new object[] { modelBuilder });
        }
    }
}