// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RFFM.Api.Infrastructure.Persistence;

#nullable disable

namespace RFFM.Api.Infrastructure.Migrations.Federation
{
    [DbContext(typeof(FederationDbContext))]
    [Migration("20260928075858_AddSquadHistory")]
    partial class AddSquadHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("federation")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RFFM.Api.Domain.Entities.Federation.FederationSetting", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CompetitionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CompetitionName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("GroupId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GroupName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<string>("TeamId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TeamName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsPrimary");

                    b.ToTable("FederationSettings", "federation");
                });

            modelBuilder.Entity("RFFM.Api.Domain.Entities.Federation.RffmSeasonPreference", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RffmSeasonPreferences", "federation");
                });

            modelBuilder.Entity("RFFM.Api.Domain.Entities.Federation.SquadHistory.SquadHistoryEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");


                    b.Property<int?>("CallUps")
                        .HasColumnType("integer");

                    b.Property<string>("ClubName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CompetitionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CompetitionName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Goals")
                        .HasColumnType("integer");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsIncomplete")
                        .HasColumnType("boolean");


                    b.Property<string>("PlayerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("RedCards")
                        .HasColumnType("integer");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<string>("SeasonName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int?>("Starts")
                        .HasColumnType("integer");

                    b.Property<string>("TeamCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("TeamPoints")
                        .HasColumnType("integer");

                    b.Property<int>("TeamPosition")
                        .HasColumnType("integer");

                    b.Property<string>("TeamShieldUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("YellowCards")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("SquadHistoryEntries", "federation");
                });

            modelBuilder.Entity("RFFM.Api.Domain.Entities.Federation.SquadHistory.SquadHistoryReport", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");


                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("FailedPlayers")
                        .HasColumnType("integer");


                    b.Property<int?>("PreviousSeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("ProcessedPlayers")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TeamCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("TotalPlayers")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TeamCode", "SeasonId")
                        .IsUnique();

                    b.ToTable("SquadHistoryReports", "federation");
                });

            modelBuilder.Entity("RFFM.Api.Domain.Entities.Federation.SquadHistory.SquadHistorySubscriber", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<bool>("Notified")
                        .HasColumnType("boolean");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReportId", "UserId")
                        .IsUnique();

                    b.ToTable("SquadHistorySubscribers", "federation");
                });

            modelBuilder.Entity("RFFM.Api.Domain.Entities.Federation.SquadHistory.SquadHistoryEntry", b =>
                {
                    b.HasOne("RFFM.Api.Domain.Entities.Federation.SquadHistory.SquadHistoryReport", null)
                        .WithMany("Entries")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RFFM.Api.Domain.Entities.Federation.SquadHistory.SquadHistorySubscriber", b =>
                {
                    b.HasOne("RFFM.Api.Domain.Entities.Federation.SquadHistory.SquadHistoryReport", null)
                        .WithMany("Subscribers")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RFFM.Api.Domain.Entities.Federation.SquadHistory.SquadHistoryReport", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Subscribers");
                });
#pragma warning restore 612, 618
        }
    }
}
